'use strict';
let history124={epoch:-1,received:{rows:[],pages:1},sent:{rows:[],pages:1},views:{rows:[],pages:1}};
function historyState124(){if(history124.epoch!==O.epoch)history124={epoch:O.epoch,received:{rows:[],pages:1},sent:{rows:[],pages:1},views:{rows:[],pages:1}};return history124[tapTab]}
async function refreshHistory124(kind=tapTab,more=false,force=false){historyState124();const h=history124[kind],epoch=O.epoch;if(h.busy||!more&&!force&&Date.now()-(h.updated||0)<10000)return;h.busy=true;try{let cursor=more?h.cursor:null,rows=more?h.rows.slice():[],pages=more?1:h.pages;for(let i=0;i<pages;i++){const params=new URLSearchParams({limit:'100'});if(kind==='views')params.set('group_visits','true');if(cursor){params.set('before',cursor.before);params.set('before_id',cursor.before_id)}const result=await remote('GET','/v1/activity/'+kind+'?'+params);if(epoch!==O.epoch)return;rows.push(...(result.events||[]));cursor=result.next_cursor;O.activitySnapshots[kind==='views'?'visit':'tap']=result.as_of;if(!cursor)break}const unique=new Map();for(const r of rows){let id;if(r.locked){const key='locked-event-'+r.event_id;id=O.ids.get(key);if(id===undefined){id=people.length;O.ids.set(key,id);people.push({id,name:'Profilo riservato'})}Object.assign(people[id],{photo:r.photo,distance:r.distance_m??Infinity,distanceHidden:r.distance_m==null})}else id=person(r);if(id!==null)unique.set(r.event_id,{...r,id,time:Date.parse(r.occurred_at)})}h.rows=[...unique.values()].sort((a,b)=>b.time-a.time||b.event_id-a.event_id);h.cursor=cursor;h.loaded=true;h.updated=Date.now();if(more)h.pages++;}catch(e){h.error=e.message;if(force||more)toast(e.message)}finally{h.busy=false;if(epoch===O.epoch&&tab==='taps'&&!document.querySelector('.overlay'))renderTaps()}}
const activityOnline124=activityOnline;activityOnline=async function(){await activityOnline124();if(tab==='taps'&&!document.querySelector('.overlay'))await refreshHistory124()};
const ackActivity124=ackActivityOnline;ackActivityOnline=async function(){await ackActivity124();historyState124().updated=0;await refreshHistory124(tapTab,false,true)};
function activityTab124(key){tapTab=key;renderTaps();refreshHistory124(key,false,true)}
function activityStamp124(time){return new Date(time).toLocaleString('it-IT',{timeZone:'Europe/Rome',day:'2-digit',month:'2-digit',year:'2-digit',hour:'2-digit',minute:'2-digit'})}
renderActivityOnline=function(){const h=historyState124(),rows=h.rows.filter(v=>!state.blocked.includes(v.id)&&people[v.id]),unread=rows.filter(v=>v.unread).length;const tile=v=>{const p=people[v.id],title=v.locked?'Profilo riservato':p.name;const distance=p.distanceHidden||!Number.isFinite(p.distance)?'':p.distance>=1000?(p.distance/1000).toFixed(1).replace('.',',')+' km':p.distance+' m';return `<button class="activitytile124 ${v.unread?'new124':''} ${v.locked?'locked124':''}" data-event-id="${v.event_id}" aria-label="${esc(title)} · ${esc(activityStamp124(v.time))}${v.unread?' · Nuovo':''}" onclick="${v.locked?"limit102('Altri profili, con Extra','Il piano Free mostra cinque profili. Distanza e orario delle altre visite rimangono visibili.')":`profile(${v.id})`}"><img src="${esc(p.photo||'placeholder.svg')}" alt="">${v.unread?'<span class="newactivity124">Nuovo</span>':''}${tapTab==='views'&&v.visit_count>1?`<span class="visitcount125" aria-label="${v.visit_count} visite">×${v.visit_count}</span>`:''}<span class="activitykind124">${icon(v.locked?'lock':tapTab==='views'?'eye':'bolt')}</span><span class="activitycaption124"><b>${esc(title)}</b>${distance?`<small>${esc(distance)}</small>`:''}<time datetime="${new Date(v.time).toISOString()}">${esc(activityStamp124(v.time))}</time></span></button>`};document.querySelector('#app').innerHTML=`<div class="activity102 activity124"><p class="eyebrow98">CHI HA NOTATO TE</p><h1>Tap e visite<span>.</span></h1><p class="activityintro102">Tutte le tue connessioni, dalla più recente.</p><div class="activitytabs102" role="group" aria-label="Tipo di attività">${[['received','Ricevuti'],['sent','Inviati'],['views','Visite']].map(([key,label])=>`<button class="${tapTab===key?'active':''}" aria-pressed="${tapTab===key}" onclick="activityTab124('${key}')"><span>${label}</span></button>`).join('')}</div>${unread?`<div class="activitysummary113"><span><b>${unread} ${unread===1?'nuova attività':'nuove attività'}</b><small>Le nuove restano evidenziate nella griglia.</small></span><button onclick="ackActivityOnline()">Segna come letti</button></div>`:''}${tapTab==='views'&&rows.some(v=>v.locked)?'<div class="activitynotice102">Free mostra cinque profili. Gli altri restano sfocati, con distanza e orario visibili.</div>':''}<div class="activitygrid124">${rows.map(tile).join('')}</div>${!rows.length?`<div class="activityempty102">${icon(tapTab==='views'?'eye':'bolt')}<h2>${!h.loaded?'Caricamento…':tapTab==='views'?'Ancora nessuna visita':'Ancora nessun Tap'}</h2><p>${h.error?esc(h.error):'Le attività rimarranno qui anche nei giorni successivi.'}</p>${h.error?'<button class="pill" onclick="refreshHistory124(tapTab,false,true)">Riprova</button>':''}</div>`:''}${h.cursor?`<button class="historymore124" onclick="refreshHistory124(tapTab,true)" ${h.busy?'disabled':''}>${h.busy?'Caricamento…':'Mostra attività precedenti'} ${icon('chevron')}</button>`:''}</div>`};
function updateChatPeer124(id){const p=people[id],peer=document.querySelector('.conversationhead .person');if(!p||!peer)return;const distance=!p.distanceHidden&&Number.isFinite(p.distance)?(p.distance>=1000?(p.distance/1000).toFixed(1).replace('.',',')+' km':p.distance+' m'):'';peer.innerHTML=`<img src="${esc(p.photo||'placeholder.svg')}" alt=""><span class="chatidentity124"><span class="chatname124"><b>${esc(p.name)}</b>${p.online?'<i class="chatonline124" role="img" aria-label="Online"></i>':''}</span>${distance?`<small class="chatdistance124">${esc(distance)}</small>`:''}</span>`}
const chat124=chat;chat=async function(id,draft){const task=chat124(id,draft);updateChatPeer124(id);await task;updateChatPeer124(id)};

const block124=block;block=async function(id){await block124(id);if(state.blocked.includes(id)){history124.epoch=-1;if(tab==='taps'&&!document.querySelector('.overlay')){renderTaps();await refreshHistory124(tapTab,false,true)}}};
