"use strict";
paths.location="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z M15 10a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z";paths.next="m9 5 7 7-7 7";
const sendBusy127=new Set(),sendBase127=send;
send=async function(e,id){e.preventDefault();if(sendBusy127.has(id))return;sendBusy127.add(id);try{await sendBase127(e,id)}finally{sendBusy127.delete(id)}};
const polishBase127=polishMessages120;
polishMessages120=function(){polishBase127();const page=document.querySelector('.chatpage');if(!page)return;page.querySelector('.send')?.remove();const input=page.querySelector('#message');if(input){input.setAttribute('enterkeyhint','send');if(!input.dataset.enter127){input.dataset.enter127='1';input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.isComposing){e.preventDefault();input.closest('form').requestSubmit()}})}}fitChatViewportOnline()};
function coordinates127(text){const match=typeof text==='string'&&text.match(/^📍 Posizione attuale\nhttps:\/\/maps\.google\.com\/\?q=(-?\d+(?:\.\d+)?),(-?\d+(?:\.\d+)?)$/);if(!match)return null;const latitude=Number(match[1]),longitude=Number(match[2]);return Number.isFinite(latitude)&&Math.abs(latitude)<=90&&Number.isFinite(longitude)&&Math.abs(longitude)<=180?{latitude,longitude}:null}
const messageBase127=messageHTML;messageHTML=function(m,id,index){const point=m?.type==='text'&&coordinates127(m.text);if(!point)return messageBase127(m,id,index);return `<button class="location127" onclick="openLocation127(${point.latitude},${point.longitude})">${icon('location')}<span><b>Posizione attuale</b><small>Apri sulla mappa</small></span>${icon('next')}</button>`};
function sendLocation127(id){return openLocationPicker128(id)}
async function openLocation127(latitude,longitude){try{const result=await bridge('openLocation',{latitude,longitude});if(result.status!==200)throw Error(result.data?.detail||'Mappa non disponibile')}catch(e){toast(e.message)}}
let fullHeight127=innerHeight;
fitChatViewportOnline=function(){const page=document.querySelector('.chatpage');if(!page)return;const viewport=window.visualViewport,native=Number(window.prismChatHeight127);let height=viewport?.height||innerHeight;if(native>0)height=Math.min(height,native);if(document.activeElement?.id!=='message'&&!window.prismKeyboard127)fullHeight127=Math.max(fullHeight127,innerHeight);const keyboard=window.prismKeyboard127===true||document.activeElement?.id==='message'&&height<fullHeight127-100;page.classList.toggle('keyboard127',keyboard);page.style.top=(viewport?.offsetTop||0)+'px';page.style.height=height+'px';page.style.bottom='auto';page.style.width='100%';page.style.maxWidth='650px'};
window.prismKeyboardChanged127=function(height,open){window.prismChatHeight127=height;window.prismKeyboard127=open;fitChatViewportOnline();requestAnimationFrame(fitChatViewportOnline)};
window.visualViewport?.addEventListener('resize',()=>fitChatViewportOnline());window.visualViewport?.addEventListener('scroll',()=>fitChatViewportOnline());document.addEventListener('focusout',()=>setTimeout(fitChatViewportOnline,100));
