"use strict";
const polishBase128=polishMessages120;
polishMessages120=function(){polishBase128();const page=document.querySelector('.chatpage');if(!page)return;const actions=page.querySelector('.composeractions126');if(actions&&!actions.querySelector('.gps128')){const button=document.createElement('button');button.type='button';button.className='gps128';button.setAttribute('aria-label','Invia posizione');button.innerHTML=icon('location');button.onclick=()=>openLocationPicker128(Number(page.dataset.chatId97));actions.querySelector('.emoji126')?.after(button)}mountMaps128()};
function mapHTML128(latitude,longitude){return `<div class="map128" data-lat128="${latitude}" data-lon128="${longitude}"><div class="maptiles128"></div><div class="mapstatus128" role="status">Caricamento mappa…</div><div class="mappin128">${icon('location')}</div><span class="mapcredit128">© OpenStreetMap contributors</span></div>`}
const messageBase128=messageHTML;messageHTML=function(m,id,index){const point=m?.type==='text'&&coordinates127(m.text);if(!point)return messageBase128(m,id,index);return `<button class="location128" aria-label="Apri posizione sulla mappa" onclick="openLocation127(${point.latitude},${point.longitude})">${mapHTML128(point.latitude,point.longitude)}<span class="mapcaption128"><span><b>Posizione condivisa</b><small>Apri sulla mappa</small></span>${icon('next')}</span></button>`};
const mapObserver128=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){paintMap128(entry.target);mapObserver128.unobserve(entry.target)}},{threshold:.01});
const trackedMaps128=new Set();const resizeMaps128=new ResizeObserver(entries=>{for(const entry of entries){const map=entry.target,rect=map.getBoundingClientRect();if(map.dataset.painted128&&rect.bottom>0&&rect.top<innerHeight&&(Math.abs(Number(map.dataset.width128)-rect.width)>1||Math.abs(Number(map.dataset.height128)-rect.height)>1))paintMap128(map)}});
function mountMaps128(){for(const map of trackedMaps128)if(!map.isConnected){resizeMaps128.unobserve(map);mapObserver128.unobserve(map);trackedMaps128.delete(map)}for(const map of document.querySelectorAll('.map128:not([data-mounted128])')){map.dataset.mounted128='1';trackedMaps128.add(map);resizeMaps128.observe(map);mapObserver128.observe(map)}}
function paintMap128(map){if(!map.isConnected)return;const latitude=Number(map.dataset.lat128),longitude=Number(map.dataset.lon128),status=map.querySelector('.mapstatus128');if(Math.abs(latitude)>85.05112878){status.textContent='Apri la posizione nella mappa';return}const zoom=16,n=2**zoom,lat=latitude*Math.PI/180,x=(longitude+180)/360*n,y=(1-Math.asinh(Math.tan(lat))/Math.PI)/2*n,rect=map.getBoundingClientRect(),width=rect.width,height=rect.height;let loaded=0,failed=0,total=0;const plane=map.querySelector('.maptiles128');plane.replaceChildren();map.dataset.painted128='1';map.dataset.width128=width;map.dataset.height128=height;for(let tileX=Math.floor(x-width/512);tileX<=Math.floor(x+width/512);tileX++)for(let tileY=Math.floor(y-height/512);tileY<=Math.floor(y+height/512);tileY++){const left=width/2+(tileX-x)*256,top=height/2+(tileY-y)*256;if(left>=width||top>=height||left+256<=0||top+256<=0||tileY<0||tileY>=n)continue;total++;const img=document.createElement('img');img.alt='';img.draggable=false;img.style.left=left+'px';img.style.top=top+'px';img.onload=()=>{loaded++;if(loaded+failed===total){status.hidden=failed===0;if(failed)status.textContent='Mappa parzialmente disponibile · Tocca per aprire'}};img.onerror=()=>{failed++;status.hidden=false;status.textContent='Mappa non disponibile · Tocca per aprire'};img.src='https://tile.openstreetmap.org/'+zoom+'/'+((tileX%n+n)%n)+'/'+tileY+'.png';plane.append(img)}}
let pickerSession128=null;
function closeLocationPicker128(){pickerSession128=null;document.querySelector('.locationpicker128')?.remove();fitChatViewportOnline();document.querySelector('#message')?.focus({preventScroll:true})}
async function openLocationPicker128(id){if(pickerSession128)return;document.activeElement?.blur();const session={id,epoch:O.epoch,point:null,sending:false};pickerSession128=session;const sheet=document.createElement('section');sheet.className='locationpicker128';sheet.setAttribute('role','dialog');sheet.setAttribute('aria-modal','true');sheet.setAttribute('aria-label','Invia posizione attuale');sheet.innerHTML=`<div class="locationsheet128"><div class="locationgrab128"></div><header><div><h2>La tua posizione</h2><p>Condividi il punto in cui ti trovi adesso.</p></div><button type="button" aria-label="Chiudi posizione" onclick="closeLocationPicker128()">${icon('close')}</button></header><div class="locationpreview128"><div class="locationloading128" role="status">Ricerca della posizione…</div></div><footer><button class="primary wide" disabled onclick="confirmLocation128()">Invia posizione attuale</button><button class="locationcancel128" onclick="closeLocationPicker128()">Annulla</button></footer></div>`;document.body.append(sheet);try{const result=await bridge('locate');if(pickerSession128!==session||session.epoch!==O.epoch||!O.me)return closeStalePicker128(session);if(result.status!==200)throw Error(result.data?.detail||'Posizione non disponibile');const p=result.data;if(!Number.isFinite(p?.latitude)||Math.abs(p.latitude)>90||!Number.isFinite(p.longitude)||Math.abs(p.longitude)>180)throw Error('Posizione non valida');session.point=p;sheet.querySelector('.locationpreview128').innerHTML=mapHTML128(p.latitude,p.longitude);sheet.querySelector('.primary').disabled=false;mountMaps128()}catch(e){if(pickerSession128!==session)return;const preview=sheet.querySelector('.locationpreview128');preview.innerHTML='<div class="locationerror128"><b>Posizione non disponibile</b><p>'+esc(e.message)+'</p><button class="pill" onclick="retryLocation128('+id+')">Riprova</button></div>'}}
function closeStalePicker128(session){if(pickerSession128===session){pickerSession128=null;document.querySelector('.locationpicker128')?.remove()}}
function retryLocation128(id){closeStalePicker128(pickerSession128);openLocationPicker128(id)}
async function confirmLocation128(){const session=pickerSession128;if(!session?.point||session.sending||session.epoch!==O.epoch)return;session.sending=true;const button=document.querySelector('.locationpicker128 .primary');button.disabled=true;button.textContent='Invio in corso…';try{const p=session.point;await sendContentOnline(session.id,{type:'text',text:'📍 Posizione attuale\nhttps://maps.google.com/?q='+p.latitude.toFixed(6)+','+p.longitude.toFixed(6)});if(O.pageChat===session.id)renderCurrentMessagesOnline(session.id);closeStalePicker128(session);toast('Posizione inviata')}catch(e){toast(e.message)}finally{session.sending=false;if(button.isConnected){button.disabled=false;button.textContent='Invia posizione attuale'}}}
const backBase128=window.prismBack;window.prismBack=function(){if(pickerSession128){closeLocationPicker128();return}backBase128()};
