"use strict";
let exploreCity137=null,cityCatalog137=null,exploreRequest137=0,discreetBusy137=false;
function ghost137(){return '<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 20V9a7 7 0 0 1 14 0v11l-3-2-4 2-4-2-3 2Z"/><path d="M9 9h.01M15 9h.01" stroke-width="3"/></svg>'}
function globe137(){return '<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c5 5 5 13 0 18-5-5-5-13 0-18Z"/></svg>'}
function discreetOn137(){return extra101()&&O.me?.discreet_mode===true}
function decorateExtra137(){
 if(!window.signedIn)return;
 const paid=extra101(),nav=document.querySelector('#nav .extra102');
 if(nav){nav.setAttribute('aria-label',paid?'Esplora altre città':'Piano Extra');nav.classList.toggle('explorenav137',paid);nav.classList.toggle('exploreselected137',paid&&!!exploreCity137);const key=paid?'city':'plan';if(nav.dataset.extra137!==key){nav.dataset.extra137=key;nav.innerHTML='<span>'+(paid?globe137():icon('extra'))+'</span>';nav.onclick=()=>extra101()?openCities137():planPage101()}}
 const home=document.querySelector('.homebrand121');if(home&&!home.querySelector('.ghost137')){const b=document.createElement('button');b.className='ghost137';b.type='button';b.onclick=()=>toggleDiscreet137();home.querySelector('.location121')?.before(b)}
 const ghost=home?.querySelector('.ghost137');if(ghost){const on=discreetOn137();if(!ghost.querySelector('svg'))ghost.innerHTML=ghost137();ghost.classList.toggle('on137',on);ghost.classList.toggle('locked137',!paid);ghost.setAttribute('aria-label',paid?'Modalità discreta '+(on?'attiva':'disattivata'):'Modalità discreta · PRISM EXTRA');ghost.setAttribute('aria-pressed',String(on));ghost.disabled=discreetBusy137;ghost.title=paid?'Visita i profili senza comparire nelle nuove visite':'Disponibile con PRISM EXTRA'}
 const page=document.querySelector('.home121');if(!page)return;
 let hint=page.querySelector('.discreethint137');if(discreetOn137()){if(!hint){hint=document.createElement('p');hint.className='discreethint137';home.after(hint)}if(!hint.querySelector('svg'))hint.innerHTML=ghost137()+' Modalità discreta attiva · Le tue nuove visite sono private.'}else hint?.remove();
 let banner=page.querySelector('.citybanner137');if(exploreCity137&&paid){if(!banner){banner=document.createElement('section');banner.className='citybanner137';page.querySelector('.homefilterbar121').before(banner)}const bannerKey=exploreCity137.id+':'+state.radiusKm;if(banner.dataset.key137!==bannerKey){banner.dataset.key137=bannerKey;banner.innerHTML='<span>'+globe137()+'</span><div><b>'+esc(exploreCity137.name)+'</b><small>Profili entro '+state.radiusKm+' km dal centro città</small></div><button onclick="leaveCity137()" aria-label="Torna vicino a me">'+icon('close')+'</button>';}if(filter!=='Preferiti'){const subtitle=page.querySelector('.homeresults121 small');if(subtitle.textContent!=='Dal centro città')subtitle.textContent='Dal centro città';const note=page.querySelector('.nearhint100');const text='Distanze dal centro di '+exploreCity137.name+' · Le storie restano vicine a te.';if(note&&note.textContent!==text)note.textContent=text}}else banner?.remove();
}
const resetBase137=resetOnline;resetOnline=function(){exploreCity137=null;cityCatalog137=null;exploreRequest137++;discreetBusy137=false;resetBase137()};
const showBase137=show;show=function(t){showBase137(t);decorateExtra137()};
const polishBase137=polishOnline;polishOnline=function(){polishBase137();decorateExtra137()};
const syncBase137=syncPlan118;syncPlan118=async function(){const epoch=O.epoch;await syncBase137();if(epoch!==O.epoch||!O.me)return;O.me.discreet_mode=entitlement118?.discreet_mode===true&&extra101();if(!extra101()&&exploreCity137){exploreCity137=null;O.near.clear();exploreRequest137++;if(tab==='near'&&!document.querySelector('.overlay'))renderNearby100();if(O.me.latitude!=null)await nearbyOnline();}decorateExtra137()};
async function toggleDiscreet137(){if(!extra101()){planPage101();return}if(discreetBusy137)return;const epoch=O.epoch,next=!discreetOn137();discreetBusy137=true;decorateExtra137();try{const r=await remote('PUT','/v1/me/discreet',{enabled:next});if(epoch!==O.epoch||!O.me)return;O.me.discreet_mode=r.enabled===true;if(entitlement118)entitlement118.discreet_mode=O.me.discreet_mode;toast(O.me.discreet_mode?'Modalità discreta attiva':'Modalità discreta disattivata')}catch(e){if(epoch===O.epoch)toast(e.message)}finally{if(epoch===O.epoch){discreetBusy137=false;decorateExtra137()}}}
const nearBase137=nearbyOnline;
nearbyOnline=async function(mode='all'){
 const epoch=O.epoch,revision=O.revision,city=extra101()?exploreCity137?.id||null:null,request=++exploreRequest137;
 const data=await remote('GET','/v1/nearby?radius_km='+state.radiusKm+'&mode='+encodeURIComponent(mode)+'&limit=60'+(city?'&city_id='+encodeURIComponent(city):''));
 if(epoch!==O.epoch||city!==(extra101()?exploreCity137?.id||null:null)||request!==exploreRequest137)return;
 if(mode==='all')O.near.clear();for(const row of data.profiles||[]){if(revision!==O.revision)delete row.favorite;const id=person(row);if(id!==null){people[id].exploreDistance137=city?row.explore_distance_m:null;people[id].exploreCity137=city;O.near.add(id)}}
 if(!(typeof autoBusy139!=='undefined'&&autoBusy139)&&!document.querySelector('.overlay')&&(tab==='near'||tab==='likes')){showOriginalOnline(tab);polishOnline();decorateExtra137()}
};
const refreshBase137=refresh9;refresh9=async function(){if(!exploreCity137||!extra101())return refreshBase137();if(refreshBusy9||!window.signedIn)return;refreshBusy9=true;try{await nearbyOnline();await storiesOnline();updatedAt100=Date.now();refreshSoundOnline();toast('Profili della città aggiornati')}catch(e){toast(e.message)}finally{refreshBusy9=false;resetPull100();if(tab==='near'&&!document.querySelector('.overlay'))renderNearby100()}};
const radiusBase137=applyRadius100;applyRadius100=async function(){if(!exploreCity137)return radiusBase137();state.radiusKm=Math.min(radiusLimit101(),Number(document.querySelector('#radiusinput').value));closeOverlay();show('near');try{await nearbyOnline();await storiesOnline()}catch(e){toast(e.message)}};
async function openCities137(){if(!extra101()){planPage101();return}const epoch=O.epoch;overlay(toolbar98('Esplora altre città','PRISM EXTRA','closeOverlay()')+'<div class="citypage137"><section class="cityintro137"><span>'+globe137()+'</span><h2>Il prossimo ciao,<br>anche lontano.</h2><p>Scegli una città. La tua posizione GPS resta invariata e le storie restano quelle vicine a te.</p></section><label for="citysearch137">Cerca tra le città disponibili</label><div class="citysearch137">'+icon('search')+'<input id="citysearch137" placeholder="Roma, Milano, Barcellona…" autocomplete="off" oninput="drawCities137()"></div><button class="currentcity137" onclick="leaveCity137()">'+icon('location')+' Torna vicino a me</button><div id="cityresults137" role="status">Caricamento città…</div></div>','cities137');removeDefaultClose98();try{if(!cityCatalog137){const r=await remote('GET','/v1/explore/cities');if(epoch!==O.epoch||!extra101())return;cityCatalog137=r.cities||[]}if(document.querySelector('.cities137'))drawCities137()}catch(e){if(epoch===O.epoch&&document.querySelector('#cityresults137'))document.querySelector('#cityresults137').textContent=e.message}}
function drawCities137(){const box=document.querySelector('#cityresults137');if(!box||!cityCatalog137)return;const normal=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),query=normal(document.querySelector('#citysearch137').value.trim()),cities=cityCatalog137.filter(c=>normal(c.name+' '+c.country+' '+c.id).includes(query));box.innerHTML=cities.map(c=>'<button class="cityrow137 '+(exploreCity137?.id===c.id?'chosen137':'')+'" onclick="selectCity137(\''+esc(c.id)+'\')"><span>'+globe137()+'</span><div><b>'+esc(c.name)+'</b><small>'+esc(c.country)+'</small></div>'+icon(exploreCity137?.id===c.id?'check':'chevron')+'</button>').join('')||'<div class="cityempty137">Nessuna città trovata. Prova un altro nome tra le città disponibili.</div>'}
async function selectCity137(id){if(!extra101())return planPage101();const city=cityCatalog137?.find(c=>c.id===id);if(!city)return;exploreCity137=city;exploreRequest137++;O.near.clear();filter='Tutti';closeOverlay();show('near');try{await nearbyOnline()}catch(e){toast(e.message)}}
async function leaveCity137(){exploreCity137=null;exploreRequest137++;O.near.clear();filter='Tutti';closeOverlay();show('near');if(O.me?.latitude!=null){try{await nearbyOnline()}catch(e){toast(e.message)}}}
function cityCard137(p){if(p.exploreCity137!==exploreCity137?.id)return '';return nearbyCard100({...p,distance:p.exploreDistance137??0,distanceHidden:p.exploreDistance137==null})}
const renderNearBase137=renderNearby100;
const planBase137=planPage101;planPage101=function(){planBase137();const list=document.querySelector('.extrafeatures120');if(!list||list.querySelector('.feature137'))return;for(const [glyph,title,paid] of [[globe137(),'Esplora altre città','Incluso'],[ghost137(),'Modalità discreta','Inclusa']])list.insertAdjacentHTML('beforeend','<article class="feature137">'+glyph+'<div><h3>'+title+'</h3><p>Free: Non inclusa</p></div><strong>'+paid+'</strong></article>');list.insertAdjacentHTML('afterend','<p class="albumfoot120">Esplora le città disponibili senza cambiare la posizione GPS. Con il fantasmino attivo, le nuove visite al profilo non vengono registrate; le visite precedenti restano visibili.</p>')};

function cityRender137(){state.radiusKm=Math.min(state.radiusKm||5,radiusLimit101());const located=O.me?.latitude!=null||!!exploreCity137,list=people.filter(p=>!p.locked&&!state.blocked.includes(p.id)&&(filter==='Preferiti'?state.favorites.includes(p.id):located&&O.near.has(p.id)&&(!!exploreCity137||p.distanceHidden||p.distance<=(state.radiusKm||5)*1000)&&(filter!=='Online'||p.online)));document.querySelector('#app').innerHTML=`<div class="near100 home121"><div id="pull100" class="ptr100 ${refreshBusy9?'loading':''}" role="status" aria-live="polite">${icon('refresh')}<span>${refreshBusy9?'Aggiornamento…':'Tira per aggiornare'}</span></div><div class="homebrand121"><h1>Esplora</h1><button onclick="filters()" class="location121" aria-label="Filtri">${icon('settings')}<span>${state.radiusKm} km</span></button></div><section class="homestories121"><div class="homesection121"><h2>Storie qui vicino</h2><button onclick="addStory()">${icon('plus')} Crea</button></div>${storyStrip()}</section><div class="homefilterbar121"><div class="nearfilters100" role="group" aria-label="Visualizza profili">${['Tutti','Online','Preferiti'].map(v=>`<button class="${filter===v?'active':''}" aria-pressed="${filter===v}" onclick="filter='${v}';show('near')">${v==='Online'?'<i class="onlinedot121"></i>':v==='Preferiti'?icon('star'):''}${v}</button>`).join('')}</div></div><div class="homeresults121"><span>${filter==='Online'?'Online adesso':filter==='Preferiti'?'I tuoi preferiti':'Scopri chi c’è'}</span><small>${filter==='Preferiti'?'Ovunque':`Entro ${state.radiusKm} km`}</small></div>${list.length?`<div class="grid">${list.map(p=>exploreCity137&&filter!=='Preferiti'?cityCard137(p):nearbyCard100(p)).join('')}</div>`:`<section class="homeempty121"><span>${icon(filter==='Preferiti'?'star':!located?'compass':filter==='Online'?'chat':'compass')}</span><h2>${filter==='Preferiti'?'Le persone da ritrovare.':!located?'Il prossimo ciao è vicino.':filter==='Online'?'Qui ora è tranquillo.':'Allarga le tue possibilità.'}</h2><p>${filter==='Preferiti'?'Salva i profili con il cuore: li ritrovi qui, ovunque siano.':!located?'Consenti la posizione per vedere profili e storie nella tua zona.':filter==='Online'?'Prova Tutti per scoprire anche chi tornerà più tardi.':'Non ci sono profili in questo raggio. Prova una distanza diversa.'}</p><button class="primary" onclick="${!located?'refresh9()':filter==='Online'?"filter='Tutti';show('near')":'filters()'}">${!located?'Attiva posizione':filter==='Online'?'Mostra tutti':'Modifica distanza'}</button></section>`}<p class="nearhint100">${updatedAt100?'Aggiornato alle '+new Date(updatedAt100).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'}):'Tira verso il basso per aggiornare'}</p><button class="refreshaccessible100" onclick="refresh9()">Aggiorna profili</button></div>`};
renderNearby100=function(){if(exploreCity137&&extra101())cityRender137();else renderNearBase137();decorateExtra137()};
