'use strict';
/* Exact home hierarchy: title/filter, stories, portraits, flat navigation. */
const homeCardBase163=nearbyCard100;
nearbyCard100=function(p){let card=homeCardBase163(p).replace('<button class="card"','<button class="profile163"').replace(/<span class="star">[\s\S]*?<\/span>/,'').replace(esc(p.name)+', '+p.age,esc(p.name));const saved=state.favorites.includes(p.id);return '<div class="card homecard163" onclick="if(event.target===this)profile('+p.id+')">'+card+'<button class="favorite163 '+(saved?'saved163':'')+'" aria-label="'+(saved?'Rimuovi':'Aggiungi')+' '+esc(p.name)+' '+(saved?'dai':'ai')+' preferiti" aria-pressed="'+saved+'" '+(O.favoritePending.has(p.id)?'disabled':'')+' onclick="event.stopPropagation();favoritePublic99('+p.id+')">'+icon('heart')+'</button></div>'};
const storiesBase163=storyStrip;
storyStrip=function(){const s=storiesBase163();if(activeStories().length)return s;const template=document.createElement('template');template.innerHTML=s;const own=template.content.querySelector('.story'),ring=own?.querySelector('.ring.blank');if(ring){ring.innerHTML=icon('plus');own.querySelector('.plusbadge')?.remove();}return template.innerHTML};
const distanceBase163=filters;
function homeDistance163(){distanceBase163()}
function setHomeFilter163(value){filter=value;closeOverlay();show('near')}
function homeActions163(){overlay('<div class="homeactions163">'+toolbar98('Esplora','Filtri e azioni','closeOverlay()')+'<div class="homeactionbody163"><div class="homechoices163" role="group" aria-label="Visualizza profili">'+['Tutti','Online','Preferiti'].map(v=>'<button aria-pressed="'+(filter===v)+'" class="'+(filter===v?'active':'')+'" onclick="setHomeFilter163(\''+v+'\')">'+v+'</button>').join('')+'</div><button onclick="homeDistance163()">'+icon('settings')+'<span><b>Distanza di ricerca</b><small>'+state.radiusKm+' km</small></span>'+icon('chevron')+'</button><button onclick="openLives139()">'+liveIcon139()+'<span><b>Live</b><small>Dirette da tutto il mondo</small></span>'+icon('chevron')+'</button><button onclick="closeOverlay();toggleDiscreet137()">'+ghost137()+'<span><b>Modalità discreta</b><small>'+(discreetOn137()?'Attiva':'Visita i profili in privato · EXTRA')+'</small></span>'+icon('chevron')+'</button><button onclick="openCities137()">'+globe137()+'<span><b>Esplora altre città</b><small>Scopri persone altrove · EXTRA</small></span>'+icon('chevron')+'</button><button onclick="addStory()">'+icon('plus')+'<span><b>Crea una storia</b><small>Una foto o un pensiero</small></span>'+icon('chevron')+'</button></div></div>','homeactions163');removeDefaultClose98()}
filters=function(){if(tab==='near'&&document.querySelector('.home121'))return homeActions163();return distanceBase163()};
function homeNav163(){if(!document.querySelector('.home121'))return;const brand=document.querySelector('#nav .brandnav95');if(brand&&!brand.src.endsWith('home-mark163.svg'))brand.src='home-mark163.svg';const profile=document.querySelector('#nav .navavatar9');if(profile)profile.parentElement.innerHTML=icon('user');const world=document.querySelector('#nav .extra102');if(world&&world.dataset.homeicon163!=='1'){world.innerHTML='<span>'+globe137()+'</span>';world.dataset.homeicon163='1'}const b=document.querySelector('.homebrand121 .location121');if(b){b.setAttribute('aria-label','Filtri e azioni');if(b.dataset.home163!=='1'){b.innerHTML='<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M3 4h18l-7 8v7l-4 2v-9z"/></svg>';b.dataset.home163='1'}}}
const decorateHome163=decorateExtra137;decorateExtra137=function(){decorateHome163();homeNav163()};
const polishHome163=polishOnline;polishOnline=function(){polishHome163();homeNav163()};
homeNav163();
