'use strict';
let lastAuto139=0,autoBusy139=false,liveCatalog139=[],liveRequest139=0;
function liveIcon139(){return '<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="12" height="14" rx="4"/><path d="m15 9 6-3v12l-6-3Z"/></svg>'}
const decorate139=decorateExtra137;decorateExtra137=function(){decorate139();const world=document.querySelector('#nav .explorenav137');if(world){world.classList.remove('extraactive103');world.classList.toggle('worldactive139',!!document.querySelector('.cities138'))}const bar=document.querySelector('.homefilterbar121');if(bar&&!bar.querySelector('.liveentry139')){const b=document.createElement('button');b.className='liveentry139';b.setAttribute('aria-label','Dirette da tutto il mondo');b.innerHTML=liveIcon139()+'<span>Live</span>';b.onclick=openLives139;bar.append(b)}};
const reset139=resetOnline;resetOnline=function(){lastAuto139=0;liveRequest139++;liveCatalog139=[];reset139()};
// Background refreshes must not replace the grid while the finger is scrolling.
let touching139=false,deferNear139=false,queuedNear139=false;
const nearRender139=renderNearby100;renderNearby100=function(){if(deferNear139){queuedNear139=true;return;}nearRender139()};
function flushNear139(){if(!queuedNear139||touching139||tab!=='near'||document.querySelector('.overlay'))return;queuedNear139=false;const y=window.scrollY;renderNearby100();polishOnline();window.scrollTo(0,y)}
document.addEventListener('touchend',()=>setTimeout(flushNear139,120),{passive:true});
document.addEventListener('touchstart',()=>touching139=true,{passive:true});document.addEventListener('touchend',()=>touching139=false,{passive:true});document.addEventListener('touchcancel',()=>touching139=false,{passive:true});
async function autoRefresh139(force=false){if(autoBusy139||refreshBusy9||!window.signedIn||!O.me||O.me.latitude==null||tab!=='near'||document.hidden||window.prismForeground===false||document.querySelector('.overlay')||touching139||(!force&&Date.now()-lastAuto139<60000))return;autoBusy139=true;deferNear139=true;const epoch=O.epoch;try{await nearbyOnline();if(epoch!==O.epoch)return;await storiesOnline();if(epoch!==O.epoch)return;lastAuto139=Date.now();updatedAt100=lastAuto139;queuedNear139=true}catch(e){O.syncError=e.message;lastAuto139=Date.now()}finally{autoBusy139=false;deferNear139=false;flushNear139()}}
const refreshBase139=refresh9;refresh9=async function(){await refreshBase139();lastAuto139=Date.now()};
refreshSoundOnline=function(){if(soundMutedOnline||soundContextOnline?.state!=='running')return;const now=soundContextOnline.currentTime;for(const [i,freq]of [1046.5,1318.5,1568].entries()){const osc=soundContextOnline.createOscillator(),gain=soundContextOnline.createGain(),t=now+i*.07;osc.type='triangle';osc.frequency.value=freq;gain.gain.setValueAtTime(.0001,t);gain.gain.exponentialRampToValueAtTime(.055,t+.015);gain.gain.exponentialRampToValueAtTime(.0001,t+.16);osc.connect(gain);gain.connect(soundContextOnline.destination);osc.start(t);osc.stop(t+.18)}};
setInterval(()=>autoRefresh139(),5000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)autoRefresh139(true)});
let foreground139=window.prismForeground;setInterval(()=>{const current=window.prismForeground;if(current!==false&&foreground139===false)autoRefresh139(true);foreground139=current},1000);
async function openLives139(){const run=++liveRequest139;overlay('<div class="liveshell139">'+toolbar98('Live','Da tutto il mondo','closeOverlay()')+'<div class="livecontent139"><section class="livelead139"><span>'+liveIcon139()+'</span><div><h2>Qui, adesso.<br>Insieme.</h2><p>Incontra la community in diretta, ovunque si trovi.</p></div></section><button class="primary wide startlive139" onclick="createLive139()">'+liveIcon139()+' Inizia una diretta</button><div class="liveheading139"><h3>In diretta ora</h3><button onclick="openLives139()" aria-label="Aggiorna dirette">'+icon('refresh')+'</button></div><div class="livefilter139"><input id="livequery139" placeholder="Cerca titolo, persona o paese" aria-label="Cerca dirette" oninput="drawLives139()"></div><div id="livegrid139" role="status">Caricamento dirette…</div><p class="liveprivacy139">Dirette pubbliche · Fino a 4 persone sul palco · Nessuna registrazione</p></div></div>','lives139');removeDefaultClose98();try{const data=await remote('GET','/v1/lives');if(run!==liveRequest139||!document.querySelector('.lives139'))return;liveCatalog139=data.lives||[];if(!data.available){document.querySelector('#livegrid139').innerHTML='<div class="liveempty139"><h3>Le live stanno arrivando.</h3><p>Il servizio video non è ancora collegato. Riprova tra poco.</p></div>';document.querySelector('.startlive139').disabled=true;return}drawLives139()}catch(e){if(document.querySelector('#livegrid139'))document.querySelector('#livegrid139').innerHTML='<div class="liveempty139"><h3>Non riusciamo a caricare le dirette.</h3><p>'+esc(e.message)+'</p><button onclick="openLives139()">Riprova</button></div>'}}
function drawLives139(){const grid=document.querySelector('#livegrid139');if(!grid)return;const q=(document.querySelector('#livequery139')?.value||'').toLowerCase(),rows=liveCatalog139.filter(l=>(l.title+' '+l.name+' '+l.country+' '+l.language).toLowerCase().includes(q));grid.innerHTML=rows.length?'<div class="livegrid139">'+rows.map(l=>'<button class="livecard139" onclick="enterLive139(\''+l.id+'\')"><img src="'+esc(l.photo||'placeholder.svg')+'" alt=""><span class="livechip139"><i></i> LIVE</span><span class="livecount139">'+Number(l.viewers||0)+' spettatori</span><div><small>'+esc(l.country)+' · '+esc(l.language)+'</small><h3>'+esc(l.title)+'</h3><p>'+esc(l.name)+'</p></div></button>').join('')+'</div>':'<div class="liveempty139"><span>'+liveIcon139()+'</span><h3>'+ (q?'Nessuna diretta trovata.':'Il palco è tuo.')+'</h3><p>'+(q?'Prova un altro nome o paese.':'Non ci sono dirette attive. Inizia tu e invita la community a partecipare.')+'</p></div>'}
function createLive139(){overlay('<div class="liveshell139">'+toolbar98('La tua diretta','Un palco per te e tre ospiti','openLives139()')+'<form class="livecontent139 livecreate139" onsubmit="startLive139(event)"><section class="livelead139"><span>'+liveIcon139()+'</span><div><h2>Accendi<br>la conversazione.</h2><p>Chiunque nella community può guardare. Sei tu a scegliere chi sale sul palco.</p></div></section><label>Titolo<input name="title" placeholder="Di cosa parliamo?" required maxlength="80" autocomplete="off"></label><label>Paese<input name="country" value="Italia" maxlength="60" required></label><label>Lingua<select name="language"><option>Italiano</option><option>English</option><option>Español</option><option>Français</option><option>Deutsch</option><option>Português</option></select></label><div class="liveagreement139"><b>Prima di iniziare</b><p>La diretta è pubblica. Niente nudità, contenuti sessuali o molestie. Puoi rifiutare richieste ed espellere ospiti. PRISM non registra la diretta.</p></div><label class="livecheck139"><input type="checkbox" required> Accetto le regole delle dirette pubbliche.</label><p class="liveerror139" role="alert"></p><button class="primary wide" type="submit">'+liveIcon139()+' Vai in diretta</button></form></div>','lives139');removeDefaultClose98()}
async function startLive139(e){e.preventDefault();const form=e.target,b=form.querySelector('[type=submit]');b.disabled=true;try{const data=Object.fromEntries(new FormData(form)),r=await remote('POST','/v1/lives',data);await enterLive139(r.id)}catch(err){form.querySelector('.liveerror139').textContent=err.message;b.disabled=false}}
async function enterLive139(id){if(!/^[a-f0-9-]{36}$/i.test(id))return;try{let result;if(window.PrismIOS)result=await bridge('liveOpen',{room:id});else if(window.PrismNative?.liveOpen)result=await new Promise(resolve=>{const key='liveopen'+Date.now();callbacks.set(key,{resolve,timer:setTimeout(()=>{callbacks.delete(key);resolve({status:0,data:{detail:'Impossibile aprire la diretta.'}})},10000)});PrismNative.liveOpen(key,id)});else throw Error('Installa la nuova versione di PRISM per usare le live.');if(result?.status!==200)throw Error(result?.data?.detail||'Impossibile aprire la diretta.')}catch(e){toast(e.message)}}

setInterval(async()=>{if(!window.signedIn||document.hidden||window.prismForeground===false||!document.querySelector('#livegrid139'))return;const run=liveRequest139;try{const r=await remote('GET','/v1/lives');if(run===liveRequest139&&document.querySelector('#livegrid139')&&r.available){liveCatalog139=r.lives||[];drawLives139()}}catch{}},15000);
