'use strict';
let lastAuto139=0,autoBusy139=false,liveCatalog139=[],liveRequest139=0;
function liveIcon139(){return '<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="12" height="14" rx="4"/><path d="m15 9 6-3v12l-6-3Z"/></svg>'}
const decorate139=decorateExtra137;decorateExtra137=function(){decorate139();const world=document.querySelector('#nav .explorenav137');if(world){world.classList.remove('extraactive103');world.classList.toggle('worldactive139',!!document.querySelector('.cities138'))}const bar=document.querySelector('.homefilterbar121');if(bar&&!bar.querySelector('.liveentry139')){const b=document.createElement('button');b.className='liveentry139';b.setAttribute('aria-label','Dirette da tutto il mondo');b.innerHTML=liveIcon139()+'<span>Live</span>';b.onclick=openLives139;bar.append(b)}};
const reset139=resetOnline;resetOnline=function(){lastAuto139=0;liveRequest139++;liveCatalog139=[];reset139()};
// Background refreshes must not replace the grid while the finger is scrolling.
let touching139=false,deferNear139=false,queuedNear139=false;
const nearRender139=renderNearby100;renderNearby100=function(){if(deferNear139){queuedNear139=true;return;}nearRender139()};
// Keep existing DOM nodes (especially images) during automatic refreshes.
function patchNode148(current,next){
 if(current.nodeType!==next.nodeType||current.nodeName!==next.nodeName){current.replaceWith(next);return next;}
 if(current.nodeType!==1){if(current.nodeValue!==next.nodeValue)current.nodeValue=next.nodeValue;return current;}
 for(const a of [...current.attributes])if(!next.hasAttribute(a.name))current.removeAttribute(a.name);
 for(const a of next.attributes)if(current.getAttribute(a.name)!==a.value)current.setAttribute(a.name,a.value);
 const keyed=new Map([...current.children].filter(n=>n.hasAttribute('onclick')).map(n=>[n.getAttribute('onclick'),n]));
 let cursor=current.firstChild;
 for(const wanted of [...next.childNodes]){
  let node=wanted.nodeType===1&&wanted.hasAttribute('onclick')?keyed.get(wanted.getAttribute('onclick')):cursor;
  if(node&&wanted.nodeType===1&&wanted.hasAttribute('onclick')&&!keyed.has(wanted.getAttribute('onclick')))node=null;
  if(node&&node.nodeType===1&&node.hasAttribute('onclick')&&node.getAttribute('onclick')!==wanted.getAttribute?.('onclick'))node=null;
  if(!node){node=wanted;current.insertBefore(node,cursor);}else{if(node!==cursor)current.insertBefore(node,cursor);node=patchNode148(node,wanted);}
  cursor=node.nextSibling;
 }
 while(cursor){const next=cursor.nextSibling;cursor.remove();cursor=next;}
 return current;
}
function silentNear148(){
 const home=document.querySelector('.home121');if(!home)return;
 const list=people.filter(p=>!p.locked&&!state.blocked.includes(p.id)&&(filter==='Preferiti'?state.favorites.includes(p.id):O.near.has(p.id)&&(!!exploreCity137||p.distanceHidden||p.distance<=(state.radiusKm||5)*1000)&&(filter!=='Online'||p.online)));
 const main=document.querySelector('#app'),anchor=[...home.querySelectorAll('.grid>.card')].find(n=>n.getBoundingClientRect().bottom>home.getBoundingClientRect().top),top=anchor?.getBoundingClientRect().top;
 let grid=home.querySelector('.grid');if(!grid){grid=document.createElement('div');grid.className='grid';home.querySelector('.homeresults121').after(grid);}
 const template=document.createElement('template');template.innerHTML='<div class="grid">'+list.map(p=>exploreCity137&&filter!=='Preferiti'?cityCard137(p):nearbyCard100(p)).join('')+'</div>';
 if(grid.innerHTML!==template.content.firstElementChild.innerHTML)patchNode148(grid,template.content.firstElementChild);
 let empty=home.querySelector('.homeempty121');if(list.length)empty?.remove();else if(!empty){empty=document.createElement('section');empty.className='homeempty121';empty.innerHTML='<span>'+icon(filter==='Preferiti'?'star':'compass')+'</span><h2>'+ (filter==='Preferiti'?'Le persone da ritrovare.':filter==='Online'?'Nessuno online qui, ora.':'Ancora nessun profilo qui.')+'</h2><p>'+ (filter==='Preferiti'?'Salva i profili con la stellina: li ritrovi qui, ovunque siano.':'Prova un altro filtro o modifica la distanza di ricerca.')+'</p><button class="primary" onclick="'+(filter==='Online'?"filter=\'Tutti\';show(\'near\')":'filters()')+'">'+(filter==='Online'?'Mostra tutti':'Modifica distanza')+'</button>';grid.after(empty);}
 const stories=home.querySelector('.stories');template.innerHTML=storyStrip();const next=template.content.firstElementChild;if(stories&&next&&stories.innerHTML!==next.innerHTML)patchNode148(stories,next);
 const hint=home.querySelector('.nearhint100');if(hint&&updatedAt100)hint.textContent='Aggiornato alle '+new Date(updatedAt100).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'});
 if(anchor?.isConnected&&top!==undefined){const delta=anchor.getBoundingClientRect().top-top;if(delta){if(document.body.classList.contains('androidscroll122'))main.scrollTop+=delta;else window.scrollBy(0,delta);}}
 decorateExtra137();
}
function flushNear139(){if(!queuedNear139||touching139||tab!=='near'||document.querySelector('.overlay'))return;queuedNear139=false;silentNear148()}
document.addEventListener('touchend',()=>setTimeout(flushNear139,120),{passive:true});
document.addEventListener('touchstart',()=>touching139=true,{passive:true});document.addEventListener('touchend',()=>touching139=false,{passive:true});document.addEventListener('touchcancel',()=>touching139=false,{passive:true});
async function autoRefresh139(force=false){if(autoBusy139||refreshBusy9||!window.signedIn||!O.me||O.me.latitude==null||tab!=='near'||document.hidden||window.prismForeground===false||document.querySelector('.overlay')||touching139||(!force&&Date.now()-lastAuto139<60000))return;autoBusy139=true;deferNear139=true;const epoch=O.epoch;try{await nearbyOnline();if(epoch!==O.epoch)return;await storiesOnline();if(epoch!==O.epoch)return;lastAuto139=Date.now();updatedAt100=lastAuto139;queuedNear139=true}catch(e){O.syncError=e.message;lastAuto139=Date.now()}finally{autoBusy139=false;deferNear139=false;flushNear139()}}
const refreshBase139=refresh9;refresh9=async function(){await refreshBase139();lastAuto139=Date.now()};
refreshSoundOnline=function(){if(soundMutedOnline||soundContextOnline?.state!=='running')return;const now=soundContextOnline.currentTime;for(const [i,freq]of [1046.5,1318.5,1568].entries()){const osc=soundContextOnline.createOscillator(),gain=soundContextOnline.createGain(),t=now+i*.07;osc.type='triangle';osc.frequency.value=freq;gain.gain.setValueAtTime(.0001,t);gain.gain.exponentialRampToValueAtTime(.055,t+.015);gain.gain.exponentialRampToValueAtTime(.0001,t+.16);osc.connect(gain);gain.connect(soundContextOnline.destination);osc.start(t);osc.stop(t+.18)}};
setInterval(()=>autoRefresh139(),5000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)autoRefresh139(true)});
let foreground139=window.prismForeground;setInterval(()=>{const current=window.prismForeground;if(current!==false&&foreground139===false)autoRefresh139(true);foreground139=current},1000);
async function openLives139(){const run=++liveRequest139;overlay('<div class="liveshell139">'+toolbar98('Live','Da tutto il mondo','closeOverlay()')+'<div class="livecontent139"><section class="livelead139"><span>'+liveIcon139()+'</span><div><h2>Qui, adesso.<br>Insieme.</h2><p>Incontra la community in diretta, ovunque si trovi.</p></div></section><button class="primary wide startlive139" onclick="createLive139()">'+liveIcon139()+' Inizia una diretta</button><div class="liveheading139"><h3>In diretta ora</h3><button onclick="openLives139()" aria-label="Aggiorna dirette">'+icon('refresh')+'</button></div><div class="livefilter139"><input id="livequery139" placeholder="Cerca titolo, persona o paese" aria-label="Cerca dirette" oninput="drawLives139()"></div><div id="livegrid139" role="status">Caricamento dirette…</div><p class="liveprivacy139">Dirette pubbliche · Fino a 4 persone sul palco · Nessuna registrazione</p></div></div>','lives139');removeDefaultClose98();try{const data=await remote('GET','/v1/lives');if(run!==liveRequest139||!document.querySelector('.lives139'))return;liveCatalog139=data.lives||[];if(!data.available){document.querySelector('#livegrid139').innerHTML='<div class="liveempty139"><h3>Le live stanno arrivando.</h3><p>Il servizio video non è ancora collegato. Riprova tra poco.</p></div>';document.querySelector('.startlive139').disabled=true;return}drawLives139()}catch(e){if(document.querySelector('#livegrid139'))document.querySelector('#livegrid139').innerHTML='<div class="liveempty139"><h3>Non riusciamo a caricare le dirette.</h3><p>'+esc(e.message)+'</p><button onclick="openLives139()">Riprova</button></div>'}}
function drawLives139(){const grid=document.querySelector('#livegrid139');if(!grid)return;const q=(document.querySelector('#livequery139')?.value||'').toLowerCase(),rows=liveCatalog139.filter(l=>(l.title+' '+l.name+' '+l.country+' '+l.language).toLowerCase().includes(q));grid.innerHTML=rows.length?'<div class="livegrid139">'+rows.map(l=>'<button class="livecard139" onclick="enterLive139(\''+l.id+'\')"><img src="'+esc(l.photo||'placeholder.svg')+'" alt=""><span class="livechip139"><i></i> LIVE</span><span class="livecount139">'+Number(l.viewers||0)+' spettatori</span><div><small>'+esc(l.country)+' · '+esc(l.language)+'</small><h3>'+esc(l.title)+'</h3><p>'+esc(l.name)+'</p></div></button>').join('')+'</div>':'<div class="liveempty139"><span>'+liveIcon139()+'</span><h3>'+ (q?'Nessuna diretta trovata.':'Il palco è tuo.')+'</h3><p>'+(q?'Prova un altro nome o paese.':'Non ci sono dirette attive. Inizia tu e invita la community a partecipare.')+'</p></div>'}
function createLive139(){overlay('<div class="liveshell139">'+toolbar98('La tua diretta','Un palco per te e tre ospiti','openLives139()')+'<form class="livecontent139 livecreate139" onsubmit="startLive139(event)"><section class="livelead139"><span>'+liveIcon139()+'</span><div><h2>Accendi<br>la conversazione.</h2><p>Chiunque nella community può guardare. Sei tu a scegliere chi sale sul palco.</p></div></section><label>Titolo<input name="title" placeholder="Di cosa parliamo?" required maxlength="80" autocomplete="off"></label><label>Paese<input name="country" value="Italia" maxlength="60" required></label><label>Lingua<select name="language"><option>Italiano</option><option>English</option><option>Español</option><option>Français</option><option>Deutsch</option><option>Português</option></select></label><div class="liveagreement139"><b>Prima di iniziare</b><p>La diretta è pubblica. Niente nudità, contenuti sessuali o molestie. Puoi rifiutare richieste ed espellere ospiti. PRISM non registra la diretta.</p></div><label class="livecheck139"><input type="checkbox" required> Accetto le regole delle dirette pubbliche.</label><p class="liveerror139" role="alert"></p><button class="primary wide" type="submit">'+liveIcon139()+' Vai in diretta</button></form></div>','lives139');removeDefaultClose98()}
async function startLive139(e){e.preventDefault();const form=e.target,b=form.querySelector('[type=submit]');b.disabled=true;try{const data=Object.fromEntries(new FormData(form)),r=await remote('POST','/v1/lives',data);await enterLive139(r.id)}catch(err){form.querySelector('.liveerror139').textContent=err.message;b.disabled=false}}
async function enterLive139(id){if(!/^[a-f0-9-]{36}$/i.test(id))return;try{let result;if(window.PrismIOS)result=await bridge('liveOpen',{room:id});else if(window.PrismNative?.liveOpen)result=await new Promise(resolve=>{const key='liveopen'+Date.now();callbacks.set(key,{resolve,timer:setTimeout(()=>{callbacks.delete(key);resolve({status:0,data:{detail:'Impossibile aprire la diretta.'}})},10000)});PrismNative.liveOpen(key,id)});else throw Error('Installa la nuova versione di PRISM per usare le live.');if(result?.status!==200)throw Error(result?.data?.detail||'Impossibile aprire la diretta.')}catch(e){toast(e.message)}}

setInterval(async()=>{if(!window.signedIn||document.hidden||window.prismForeground===false||!document.querySelector('#livegrid139'))return;const run=liveRequest139;try{const r=await remote('GET','/v1/lives');if(run===liveRequest139&&document.querySelector('#livegrid139')&&r.available){liveCatalog139=r.lives||[];drawLives139()}}catch{}},15000);
