'use strict';
// Keep requests bounded before entering Android's two-thread native queue.
const bridgeBase150=bridge,queued150=[],reads150=new Map();let active150=0,health150=null,healthAt150=0,healthTask150=null;
function pump150(){while(active150<2&&queued150.length){const job=queued150.shift();if(job.epoch!==O.epoch){job.reject(Object.assign(Error('Sessione cambiata'),{status:401}));continue}active150++;Promise.resolve().then(()=>bridgeBase150('api',job.args)).then(job.resolve,job.reject).finally(()=>{active150--;pump150()})}}
bridge=function(action,args={}){if(action!=='api')return bridgeBase150(action,args);const key=O.epoch+':'+args.method+':'+args.path;if(args.method==='GET'&&reads150.has(key))return reads150.get(key);const task=new Promise((resolve,reject)=>{const job={args,resolve,reject,epoch:O.epoch};if(args.method==='GET')queued150.push(job);else queued150.unshift(job);pump150()});if(args.method==='GET'){reads150.set(key,task);task.finally(()=>reads150.delete(key)).catch(()=>{})}return task};
async function serverReady150(){if(healthAt150&&Date.now()-healthAt150<60000)return health150;if(healthTask150)return healthTask150;healthTask150=bridge('api',{method:'GET',path:'/health'}).then(r=>{if(r.status===200&&r.data?.version){const v=r.data.version.split('.').map(Number);health150=v[0]>0||v[1]>3||v[1]===3&&v[2]>=28;healthAt150=Date.now()}return health150}).catch(()=>null).finally(()=>{healthTask150=null});return healthTask150}
const remoteBase150=remote;remote=async function(method,path,data){const privatePath=/^\/v1\/(calls(?:\/|$)|private-albums\/|me\/album-access(?:\/|$)|me\/albums\/[^/]+\/visibility$|profiles\/[^/]+\/private-albums$)/.test(path);if((privatePath||method==='POST'&&path.startsWith('/v1/taps/'))&&await serverReady150()===false){const e=Error('Le nuove funzioni richiedono il backend PRISM 0.3.28 o successivo. Il server deve essere aggiornato.');e.status=404;e.code='backend_update_required';throw e}try{return await remoteBase150(method,path,data)}catch(e){if(method==='GET'&&[0,502,504].includes(e.status)&&!document.hidden&&!O.backgroundSync156){await new Promise(r=>setTimeout(r,600));return remoteBase150(method,path,data)}throw e}};
let dirty150=false;
const stateRender150=renderStateOnline;renderStateOnline=function(){if(document.querySelector('.overlay')||document.querySelector('.mediasheet150')){dirty150=true;return}dirty150=false;stateRender150()};
const closeOverlay150=closeOverlay;closeOverlay=function(){closeMedia150();closeOverlay150();if(dirty150&&!document.querySelector('.overlay')){dirty150=false;stateRender150()}};
const polish150=polishMessages120;polishMessages120=function(){polish150();document.querySelectorAll('.chatpage button').forEach(b=>{if(!b.classList.contains('send'))b.type='button'})};
let media150=null,mediaGeneration150=0;
function mediaShell150(title,subtitle){closeMedia150();document.activeElement?.blur();document.querySelector('.chatoptions126')?.remove();const page=document.createElement('section');page.className='mediasheet150';page.setAttribute('role','dialog');page.setAttribute('aria-modal','true');page.setAttribute('aria-label',title);page.innerHTML='<div class="mediapanel150"><div class="grab150"></div><header><div><small>CON '+esc(people[O.pageChat]?.name||'IL DESTINATARIO')+'</small><h2>'+esc(title)+'</h2><p>'+esc(subtitle)+'</p></div><button type="button" aria-label="Chiudi" onclick="closeMedia150()">'+icon('close')+'</button></header><div class="mediacontent150"></div></div>';page.addEventListener('click',e=>{if(e.target===page)closeMedia150()});document.body.append(page);page.querySelector('header button').focus();return page.querySelector('.mediacontent150')}
function closeMedia150(){const sheet=document.querySelector('.mediasheet150');if(sheet?.dataset.sending==='true')return;sheet?.remove();media150=null;mediaGeneration150++;pendingPhoto=null}
photoChoice129=function(id){if(recording||voicePending)return toast('Termina prima la registrazione');const body=mediaShell150('Invia una foto','Scegli come vuoi condividerla.');body.innerHTML='<div class="modecards150"><button type="button" onclick="chooseChatPhoto('+id+',false)"><span>'+icon('photo')+'</span><b>Foto normale</b><small>Resta nella conversazione</small>'+icon('next')+'</button><button type="button" onclick="chooseChatPhoto('+id+',true)"><span>'+icon('clock')+'</span><b>Una sola volta</b><small>Si elimina dopo l’apertura</small>'+icon('next')+'</button></div><p class="mediahint150">La scelta è tua, ogni volta.</p>'};
chooseChatPhoto=function(id,temporary){if(recording||voicePending)return toast('Termina prima la registrazione');const body=mediaShell150(temporary?'Foto temporanea':'Invia una foto',temporary?'Un’apertura. Dieci secondi. Solo per chi la riceve.':'Una foto da ritrovare nella vostra chat.');media150={id,temporary,kind:'photo',image:null};body.innerHTML='<div class="photopreview150" id="chatphotopreview"><span>'+icon(temporary?'clock':'photo')+'</span><b>Scegli la tua foto</b><small>La vedrai qui prima di inviarla</small></div><label class="gallery150">'+icon('photo')+'<span>Scegli dalla galleria</span><input type="file" accept="image/*" onchange="previewChatPhoto(this,'+id+','+temporary+')"></label><div class="mediainfo150">'+icon(temporary?'lock':'chat')+'<p>'+(temporary?'Quando il destinatario apre la foto, non sarà più disponibile per nessuno.':'La foto sarà disponibile nella conversazione per entrambi.')+'</p></div><p class="mediaerror150" role="alert"></p><button type="button" class="primary mediaconfirm150" disabled onclick="sendChatPhoto()">Invia '+(temporary?'foto temporanea':'foto')+'</button>'};
previewChatPhoto=function(input,id,temporary){const gen=mediaGeneration150;readPhoto(input,image=>{if(gen!==mediaGeneration150||!media150||media150.id!==id)return;media150.image=image;pendingPhoto={id,temporary,image};const box=document.querySelector('#chatphotopreview');box.replaceChildren();const img=document.createElement('img');img.src=image;img.alt='Anteprima della foto da inviare';box.append(img);document.querySelector('.mediaconfirm150').disabled=false;document.querySelector('.gallery150 span').textContent='Cambia foto'})};
async function sendMedia150(payload,id){const sheet=document.querySelector('.mediasheet150');if(!sheet||sheet.dataset.sending==='true')return;sheet.dataset.sending='true';const b=sheet.querySelector('.mediaconfirm150'),label=b.textContent;b.disabled=true;b.innerHTML='<i class="spinner150"></i> Invio in corso…';sheet.querySelectorAll('button,input').forEach(x=>x.disabled=true);try{await sendContentOnline(id,payload);delete sheet.dataset.sending;closeMedia150();if(O.pageChat===id&&document.querySelector('.chatpage'))renderCurrentMessagesOnline(id);else await chat(id);toast('Inviato')}catch(e){delete sheet.dataset.sending;sheet.querySelectorAll('button,input').forEach(x=>x.disabled=false);b.textContent=label;sheet.querySelector('.mediaerror150').textContent=e.message}}
sendChatPhoto=async function(){const m=media150;if(!m?.image)return;await sendMedia150({type:m.temporary?'temporary':'photo',data:m.image},m.id)};
chooseAlbum9=async function(id){if(recording||voicePending)return toast('Termina prima la registrazione');const body=mediaShell150('Condividi un album','Le tue foto, con la persona che scegli.');media150={id,kind:'album',temporary:false,selected:null};const gen=mediaGeneration150;body.innerHTML='<div class="mediaload150"><i class="spinner150"></i> Caricamento album</div>';try{await albumsOnline();if(gen!==mediaGeneration150||!media150)return;media150.selected=albums9()[0]?.id||null;drawAlbums150()}catch(e){if(gen===mediaGeneration150)body.innerHTML='<p class="mediaerror150" role="alert">'+esc(e.message)+'</p><button type="button" class="pill" onclick="chooseAlbum9('+id+')">Riprova</button>'}};
function drawAlbums150(){const m=media150,body=document.querySelector('.mediacontent150');if(!m||!body)return;const list=albums9();body.innerHTML='<div class="mediatoggle150"><button type="button" class="'+(!m.temporary?'selected':'')+'" onclick="modeAlbum150(false)">Normale</button><button type="button" class="'+(m.temporary?'selected':'')+'" onclick="modeAlbum150(true)">'+icon('clock')+' Una sola volta</button></div><div class="albumgrid150">'+list.map(a=>'<button type="button" class="albumcard150 '+(m.selected===a.id?'selected':'')+'" onclick="selectAlbum150(\''+a.id+'\')"><img src="'+esc(a.photos[0])+'" alt="Copertina di '+esc(a.name)+'"><span class="albumcheck150">'+icon(m.selected===a.id?'check':'album')+'</span><div><b>'+esc(a.name)+'</b><small>'+a.photos.length+' foto</small></div></button>').join('')+'</div>'+(list.length?'<div class="mediainfo150">'+icon(m.temporary?'lock':'album')+'<p>'+(m.temporary?'Una sola apertura di 60 secondi per sfogliare le foto. Poi l’album condiviso non è più disponibile.':'Le foto di questo album rimangono nella vostra conversazione.')+'</p></div>':'<div class="mediaempty150">'+icon('album')+'<h3>Il tuo primo album</h3><p>Crea un album nel tuo profilo per condividerlo in chat.</p></div>')+'<p class="mediaerror150" role="alert"></p>'+(list.length?'<button type="button" class="primary mediaconfirm150" onclick="sendAlbum9(media150.id,media150.selected,media150.temporary)">Condividi '+(m.temporary?'album temporaneo':'album')+'</button>':'')+'<button type="button" class="mediasecondary150" onclick="closeMedia150();albumManager9()">Gestisci i miei album</button>'}
function modeAlbum150(temporary){if(media150){media150.temporary=temporary;drawAlbums150()}}
function selectAlbum150(id){if(media150){media150.selected=id;drawAlbums150()}}
sendAlbum9=async function(id,albumId,temporary){if(!albumId)return;await sendMedia150({type:'album',album_id:albumId,temporary:!!temporary},id)};
const reset150=resetOnline;resetOnline=function(){health150=null;healthAt150=0;O.readAck150={};dirty150=false;const sheet=document.querySelector('.mediasheet150');if(sheet)delete sheet.dataset.sending;closeMedia150();reset150()};
const back150=window.prismBack;window.prismBack=function(){if(document.querySelector('.mediasheet150'))return closeMedia150();back150()};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.querySelector('.mediasheet150')){e.preventDefault();closeMedia150()}});
