'use strict';
const P=window.P={};
const A={me:null,tab:'near',mode:'all',radius:5,near:[],profiles:new Map(),favorites:new Set(),chats:[],blocked:[],taps:{received:[],sent:[]},direction:'received',route:null,drafts:new Map(),messages:new Map(),cursors:new Map(),retry:new Map(),epoch:0,located:false,loading:false,lastHeartbeat:0};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=v=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v);
const I={chat:'M21 12a8 8 0 0 1-8 8H8l-5 2V11a8 8 0 0 1 18 1 M8 10h8 M8 14h5',user:'M16 7a4 4 0 1 1-8 0a4 4 0 0 1 8 0 M4 21a8 8 0 0 1 16 0',bolt:'M13 2L4 14h7l-1 8 10-13h-7z',star:'M12 3l2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L2 9.6l6.2-.9z',extra:'M6 4h12l4 6-10 12L2 10z M2 10h20 M6 4l6 18 6-18 M9 4l-3 6 M15 4l3 6',back:'M15 5l-7 7 7 7',close:'M6 6l12 12 M18 6L6 18',block:'M12 3a9 9 0 1 0 0 18a9 9 0 0 0 0-18 M6 6l12 12',report:'M12 3L2 21h20z M12 9v5 M12 17h.01',send:'M3 4l18 8-18 8 3-8z M6 12h15',smile:'M12 3a9 9 0 1 0 0 18a9 9 0 0 0 0-18 M8 14q4 4 8 0 M8 9h.01 M16 9h.01',settings:'M4 6h16 M4 12h16 M4 18h16 M8 3v6 M16 9v6 M10 15v6',pin:'M19 9c0 5-7 12-7 12S5 14 5 9a7 7 0 0 1 14 0 M15 9a3 3 0 1 1-6 0a3 3 0 0 1 6 0',trash:'M4 6h16 M9 6V3h6v3 M6 6l1 15h10l1-15 M10 10v7 M14 10v7',edit:'M4 20l1-5L16 4l4 4L9 19z M13 7l4 4',exit:'M10 4H4v16h6 M10 12h11 M17 8l4 4-4 4',clock:'M12 3a9 9 0 1 0 0 18a9 9 0 0 0 0-18 M12 7v5l3 2',lock:'M6 10h12v11H6z M8 10V7a4 4 0 0 1 8 0v3'};
const icon=(n,fill=false)=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${I[n]||I.user}" ${fill?'fill="currentColor"':''}/></svg>`;
const avatar=(large=false)=>`<div class="avatar ${large?'large':''}" aria-label="Foto profilo non disponibile">${icon('user')}</div>`;
const when=v=>v?new Date(v).toLocaleString('it-IT',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'';
function lastSeen(p){if(p.online)return 'Online ora';if(!p.last_seen)return 'Ultimo accesso non disponibile';let minutes=Math.max(0,Math.floor((Date.now()-new Date(p.last_seen))/60000));return minutes<1?'Attivo poco fa':minutes<60?`Attivo ${minutes} min fa`:'Ultimo accesso '+when(p.last_seen);}
const distance=p=>p.distance_m==null?'Distanza nascosta':p.distance_m>=1000?(p.distance_m/1000).toFixed(1).replace('.',',')+' km':p.distance_m+' m';
const pending=new Map();
window.prismNativeReply=(id,response)=>{const task=pending.get(id);if(task){clearTimeout(task.timer);pending.delete(id);task.resolve(response);}};
function native(action,args={}){
 if(window.PrismIOS)return PrismIOS.call(action,args);
 if(window.PrismNative){return new Promise(resolve=>{const id='r'+Date.now().toString(36)+Math.random().toString(36).slice(2);pending.set(id,{resolve,timer:setTimeout(()=>{pending.delete(id);resolve({status:0,data:{detail:'Connessione lenta. Riprova.'}});},35000)});if(action==='api')PrismNative.request(id,args.method,args.path,args.body||'');else if(action==='locate')PrismNative.locate(id);else if(action==='settings'){PrismNative.settings();window.prismNativeReply(id,{status:200,data:{}});}});}
 return Promise.resolve({status:0,data:{detail:'Apri questa versione nell’app PRISM.'}});
}
async function api(method,path,data){let response;try{response=await native('api',{method,path,body:data===undefined?'':JSON.stringify(data)});}catch{throw new Error('Connessione non disponibile. Riprova.');}if(response.status>=200&&response.status<300)return response.data||{};const error=new Error(typeof response.data?.detail==='string'?response.data.detail:response.status===429?'Troppe richieste. Attendi un minuto e riprova.':'Controlla i dati inseriti e riprova.');error.status=response.status;if(response.status===401&&!path.startsWith('/v1/auth/')){clearAccount();P.auth('login','Sessione terminata. Accedi di nuovo.');}throw error;}
function cache(p){if(uid(p.user_id)){A.profiles.set(p.user_id,{...A.profiles.get(p.user_id),...p});if(p.favorite===true)A.favorites.add(p.user_id);if(p.favorite===false)A.favorites.delete(p.user_id);}return A.profiles.get(p.user_id)||p;}
function clearAccount(){P.closeModal?.();A.epoch++;A.me=null;window.signedIn=false;A.near=[];A.profiles.clear();A.favorites.clear();A.chats=[];A.blocked=[];A.taps={received:[],sent:[]};A.route=null;A.drafts.clear();A.messages.clear();A.cursors.clear();A.retry.clear();A.located=false;document.querySelector('#nav').hidden=true;document.querySelector('#layer').innerHTML='';}
P.toast=text=>{document.querySelector('.onlinetoast')?.remove();const node=document.createElement('div');node.className='onlinetoast';node.setAttribute('role','status');node.textContent=text;document.body.append(node);setTimeout(()=>node.remove(),4500);};
P.auth=(mode='login',notice='')=>{document.querySelector('#nav').hidden=true;document.querySelector('#layer').innerHTML='';A.authMode=mode;const register=mode==='register',forgot=mode==='forgot',verify=mode==='verify';document.querySelector('#app').innerHTML=`<section class="real-auth"><img class="auth-logo" src="prism-mark.svg" alt="PRISM"><p class="eyebrow">IL PROSSIMO CIAO, VICINO.</p><h1>${register?'Il tuo spazio<br>inizia qui.':forgot?'Ritrova il tuo<br>account.':verify?'Controlla la<br>tua email.':'Bentornato<br>su PRISM.'}</h1><p class="intro">${register?'Crea il tuo account. PRISM è riservata ai maggiorenni.':forgot?'Ti invieremo un link per scegliere una nuova password.':verify?'Apri il link ricevuto, conferma l’email e poi accedi.':'Accedi per conoscere chi è vicino a te.'}</p>${!forgot&&!verify?`<div class="auth-segments"><button type="button" class="${!register?'chosen':''}" onclick="P.auth('login')">Accedi</button><button type="button" class="${register?'chosen':''}" onclick="P.auth('register')">Registrati</button></div>`:''}<form id="auth-form" onsubmit="P.submitAuth(event)">${register?'<label>Nome<input id="auth-name" autocomplete="nickname" maxlength="40" required></label><label>Data di nascita<input id="auth-birth" type="date" required></label>':''}<label>Email<input id="auth-email" type="email" autocomplete="email" maxlength="254" value="${esc(A.pendingEmail||'')}" required></label>${!forgot&&!verify?`<label>Password<input id="auth-password" type="password" autocomplete="${register?'new-password':'current-password'}" minlength="12" maxlength="128" required></label>`:''}${register?'<label class="adult-check"><input id="adult" type="checkbox" required><span>Confermo di avere almeno 18 anni.</span></label><p class="hint">Scegli una password di almeno 12 caratteri.</p>':''}<p id="auth-status" role="status" aria-live="polite">${esc(notice)}</p><button class="primary wide" id="auth-submit">${register?'Crea account':forgot?'Invia link':verify?'Invia di nuovo l’email':'Accedi'}</button></form><button type="button" class="textlink" onclick="P.auth('${forgot||verify?'login':'forgot'}')">${forgot||verify?'Torna al login':'Password dimenticata?'}</button>${!register&&!forgot&&!verify?'<button class="textlink" onclick="P.auth(\'verify\')">Hai già un account da confermare?</button>':''}<p class="auth-footer">PRISM · Anteprima online 0.11.0</p></section>`;};
P.submitAuth=async event=>{event.preventDefault();const mode=A.authMode,email=document.querySelector('#auth-email').value.trim(),button=document.querySelector('#auth-submit'),status=document.querySelector('#auth-status');button.disabled=true;status.textContent='Un momento…';A.pendingEmail=email;try{if(mode==='register'){await api('POST','/v1/auth/register',{email,password:document.querySelector('#auth-password').value,name:document.querySelector('#auth-name').value.trim(),birth_date:document.querySelector('#auth-birth').value,adult_confirmed:document.querySelector('#adult').checked});P.auth('verify','Se possibile, riceverai l’email di conferma. Controlla anche lo spam.');}else if(mode==='forgot'||mode==='verify'){await api('POST',mode==='forgot'?'/v1/auth/forgot-password':'/v1/auth/resend-verification',{email});status.textContent='Se possibile, riceverai un’email con le istruzioni. Controlla anche lo spam.';}else{await api('POST','/v1/auth/login',{email,password:document.querySelector('#auth-password').value});await enter();}}catch(error){status.textContent=error.message;if(error.status===403)status.insertAdjacentHTML('beforeend','<button type="button" class="textlink" onclick="P.auth(\'verify\')">Reinvia conferma</button>');}finally{button.disabled=false;}};
async function enter(){const me=await api('GET','/v1/me');clearAccount();A.me=me;window.signedIn=true;A.tab='near';P.show('near');heartbeat();loadTaps().catch(()=>{});}
function nav(){document.querySelector('#nav').hidden=false;document.querySelector('#nav').innerHTML=[['near','Vicino a te'],['taps','Tap'],['chat','Chat'],['extra','PRISM Extra'],['me','Il mio profilo']].map(([key,label])=>`<button aria-label="${label}" aria-current="${A.tab===key?'page':'false'}" class="${A.tab===key?'selected':''}" onclick="P.show('${key}')">${key==='near'?'<img src="prism-mark.svg" alt="">':icon(key==='taps'?'bolt':key==='me'?'user':key)}</button>`).join('');}
P.show=async tab=>{if(!A.me)return P.auth();A.tab=tab;A.route=null;document.querySelector('#layer').innerHTML='';nav();if(tab==='near')renderNear();if(tab==='taps')renderTaps();if(tab==='chat')renderChats();if(tab==='me')renderMe();if(tab==='extra')renderExtra();try{if(tab==='near'&&A.located)await loadNear();if(tab==='taps')await loadTaps();if(tab==='chat')await loadChats();}catch(error){P.toast(error.message);}};
function empty(title,text,action=''){return `<div class="real-empty">${icon('pin')}<h2>${esc(title)}</h2><p>${esc(text)}</p>${action}</div>`;}
function renderNear(){if(A.tab!=='near')return;document.querySelector('#app').innerHTML=`<section class="real-near"><div id="pull-hint" role="status"></div><div class="homebar"><div class="brand"><img src="prism-mark.svg" alt="">PRISM</div><button class="round" aria-label="Raggio di ricerca" onclick="P.filters()">${icon('settings')}</button></div><h1>Vicino a te</h1><p class="intro">${A.located?`${A.near.length} profili · entro ${A.radius} km`:'Conosci chi è qui, intorno a te.'}</p><div class="real-filters">${[['all','Tutti'],['online','Online'],['favorites','Preferiti']].map(([key,label])=>`<button class="${A.mode===key?'chosen':''}" onclick="P.filter('${key}')">${key==='favorites'?icon('star'):''}${label}</button>`).join('')}</div>${!A.located?empty('Il prossimo ciao è vicino','Consenti la posizione per vedere i profili nel raggio scelto.','<button class="primary" onclick="P.refresh()">Attiva posizione</button><button class="textlink" onclick="P.settings()">Impostazioni telefono</button>'):A.loading&&!A.near.length?empty('Cerchiamo qui vicino…','Un momento.'):A.near.length?`<div class="real-grid">${A.near.map(p=>`<button class="real-card" onclick="P.openProfile('${p.user_id}')">${avatar()}<span class="caption"><b>${p.online?'<i class="dot"></i>':''}${esc(p.name)}, ${esc(p.age)}</b><small>${distance(p)}</small></span>${A.favorites.has(p.user_id)?`<span class="star">${icon('star',true)}</span>`:''}</button>`).join('')}</div>`:empty('Ancora nessuno qui vicino',A.mode==='favorites'?'Salva un profilo con la stellina per ritrovarlo qui.':'I profili appariranno quando altre persone si registreranno in questa zona.')}<button class="textlink refresh-accessible" onclick="P.refresh()">${A.loading?'Aggiornamento…':'Aggiorna posizione e profili'}</button><p class="hint">Tira verso il basso per aggiornare.</p></section>`;}
P.settings=()=>native('settings');
async function loadNear(){const epoch=A.epoch,mode=A.mode;const data=await api('GET',`/v1/nearby?mode=${mode}&radius_km=${A.radius}`);if(epoch!==A.epoch||mode!==A.mode)return;A.near=(data.profiles||[]).filter(p=>uid(p.user_id)).map(cache);renderNear();}
P.refresh=async()=>{if(A.loading)return;A.loading=true;renderNear();try{let location=await native('locate');if(location.status!==200)throw new Error(location.data?.detail||'Posizione non disponibile');await api('PUT','/v1/me/location',location.data);A.located=true;await loadNear();P.toast('Profili aggiornati');}catch(error){P.toast(error.message);}finally{A.loading=false;renderNear();}};
P.filter=async mode=>{A.mode=mode;renderNear();if(A.located)try{await loadNear();}catch(error){P.toast(error.message);}};
P.filters=()=>modal(`<h1>Quanto vicino?</h1><p>Il piano Free cerca fino a 5 km.</p><form onsubmit="P.saveRadius(event)"><label>Raggio · km<input id="radius" type="range" min="1" max="5" value="${A.radius}" oninput="document.querySelector('#radius-label').textContent=this.value+' km'"></label><h2 id="radius-label">${A.radius} km</h2><button class="primary wide">Applica</button></form>`);
P.saveRadius=async event=>{event.preventDefault();A.radius=Number(document.querySelector('#radius').value);P.closeModal();await P.show('near');};
function layer(content,kind='real-profile'){document.querySelector('#layer').innerHTML=`<section class="${kind}" role="dialog" aria-modal="true">${content}</section>`;}
function modal(content){document.querySelector('#modal')?.remove();const node=document.createElement('div');node.id='modal';node.className='modal-shade';node.innerHTML=`<section class="modal-card" role="dialog" aria-modal="true"><button class="modal-close round" aria-label="Chiudi" onclick="P.closeModal()">${icon('close')}</button>${content}</section>`;document.body.append(node);['app','nav','layer'].forEach(id=>document.getElementById(id).inert=true);node.addEventListener('keydown',event=>{if(event.key==='Escape')P.closeModal();if(event.key==='Tab'){let controls=[...node.querySelectorAll('button,input,textarea,select')].filter(el=>!el.disabled),first=controls[0],last=controls.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}});node.querySelector('input,textarea,button:not(.modal-close)')?.focus();}
P.closeModal=()=>{document.querySelector('#modal')?.remove();['app','nav','layer'].forEach(id=>document.getElementById(id).inert=false);};
P.openProfile=async(id,fromChat=false)=>{if(!uid(id))return;const previous=A.route;A.route={type:'profile',id,previous:fromChat?previous:null};const p=A.profiles.get(id);if(p)renderProfile(p);try{const epoch=A.epoch;const data=cache(await api('GET','/v1/profiles/'+id));if(epoch===A.epoch&&A.route?.type==='profile'&&A.route.id===id)renderProfile(data);}catch(error){P.toast(error.message);if(A.route?.id===id)P.back();}};
function renderProfile(p,own=false){const tapped=(A.taps.sent.find(t=>t.user_id===p.user_id)?.sent_at),wait=tapped&&Date.now()-new Date(tapped)<86400000;layer(`<div class="public-hero">${avatar(true)}<div class="public-toolbar"><button class="round" aria-label="Indietro" onclick="P.back()">${icon('back')}</button><div>${!own?`<button class="round ${A.favorites.has(p.user_id)?'gold':''}" aria-label="Preferito" onclick="P.favorite('${p.user_id}')">${icon('star',A.favorites.has(p.user_id))}</button><button class="round" aria-label="Blocca profilo" onclick="P.confirmBlock('${p.user_id}')">${icon('block')}</button><button class="round" aria-label="Segnala profilo" onclick="P.report('${p.user_id}')">${icon('report')}</button>`:''}</div></div><div class="public-identity"><p>${own?'Il tuo profilo':esc(lastSeen(p))}</p><h1>${esc(p.name)}, ${esc(p.age)}</h1>${own?'':`<small>${distance(p)}</small>`}</div></div><div class="public-content"><section><h2>Su di me</h2><p>${esc(p.bio||'Questo profilo non ha ancora una bio.')}</p></section><section><h2>Cerco</h2><div class="detail-chips">${(p.looking_for||[]).map(v=>`<span>${esc(v)}</span>`).join('')||'<p>Non specificato</p>'}</div></section>${p.instagram||p.facebook?`<section><h2>Social</h2>${p.instagram?`<p>Instagram · @${esc(p.instagram)}</p>`:''}${p.facebook?`<p>Facebook · ${esc(p.facebook)}</p>`:''}</section>`:''}</div>${own?'':`<div class="profile-bottom"><button class="primary" onclick="P.chat('${p.user_id}')">${icon('chat')} Messaggio</button><button class="tap-button ${wait?'gold':''}" ${wait?'disabled':''} onclick="P.tap('${p.user_id}')">${icon('bolt',wait)} ${wait?'Tap inviato':'Tap'}</button></div>`}`);}
P.favorite=async id=>{try{const yes=A.favorites.has(id);await api(yes?'DELETE':'PUT','/v1/favorites/'+id);if(yes)A.favorites.delete(id);else A.favorites.add(id);if(A.route?.type==='profile'&&A.route.id===id)renderProfile(A.profiles.get(id));P.toast(yes?'Rimosso dai preferiti':'Aggiunto ai preferiti');if(A.located)await loadNear();}catch(error){P.toast(error.message);}};
P.back=()=>{P.closeModal();const previous=A.route?.previous;if(previous?.type==='chat'){A.route=previous;drawChat();return;}A.route=null;document.querySelector('#layer').innerHTML='';};
window.prismBack=()=>{if(document.querySelector('#modal'))P.closeModal();else if(A.route)P.back();else if(A.me)P.show('near');else P.auth('login');};
P.confirmBlock=id=>modal(`<h1>Bloccare ${esc(A.profiles.get(id)?.name||'questo profilo')}?</h1><p>Profili, chat e tap saranno nascosti in entrambe le direzioni.</p><button class="primary wide" onclick="P.block('${id}')">Blocca profilo</button>`);
P.block=async id=>{try{await api('PUT','/v1/blocks/'+id);A.profiles.delete(id);A.favorites.delete(id);A.near=A.near.filter(p=>p.user_id!==id);A.chats=A.chats.filter(p=>p.user_id!==id);for(const key of ['sent','received'])A.taps[key]=A.taps[key].filter(p=>p.user_id!==id);A.messages.delete(id);A.drafts.delete(id);A.retry.delete(id);A.cursors.delete(id);P.closeModal();await P.show(A.tab);P.toast('Profilo bloccato');}catch(error){P.toast(error.message);}};
P.report=id=>modal(`<h1>Segnala profilo</h1><p>Descrivi il problema.</p><form onsubmit="P.sendReport(event,'${id}')"><label>Motivo<textarea id="reason" minlength="3" maxlength="1000" required></textarea></label><button class="primary wide">Invia segnalazione</button></form>`);
P.sendReport=async(event,id)=>{event.preventDefault();try{await api('POST','/v1/reports/'+id,{reason:document.querySelector('#reason').value});P.closeModal();P.toast('Segnalazione ricevuta');}catch(error){P.toast(error.message);}};
async function loadTaps(){const epoch=A.epoch;const [received,sent]=await Promise.all([api('GET','/v1/taps?direction=received'),api('GET','/v1/taps?direction=sent')]);if(epoch!==A.epoch)return;A.taps.received=(received.taps||[]).filter(p=>uid(p.user_id)).map(cache);A.taps.sent=(sent.taps||[]).filter(p=>uid(p.user_id)).map(cache);if(A.tab==='taps')renderTaps();}
function renderTaps(){const rows=A.taps[A.direction];document.querySelector('#app').innerHTML=`<section class="real-page"><p class="eyebrow">UN PICCOLO SEGNALE</p><h1>Tap</h1><p class="intro">Chi ti nota, chi ti cerca.</p><div class="real-filters">${[['received','Ricevuti'],['sent','Inviati']].map(([key,label])=>`<button class="${A.direction===key?'chosen':''}" onclick="P.tapTab('${key}')">${label} · ${A.taps[key].length}</button>`).join('')}</div>${rows.length?rows.map(p=>`<button class="person-row" onclick="P.openProfile('${p.user_id}')">${avatar()}<span class="copy"><b>${esc(p.name)}, ${esc(p.age)}</b><small>${A.direction==='received'?'Tap ricevuto':'Tap inviato'}</small><time>${when(p.sent_at)}</time></span>${icon('bolt',A.direction==='sent')}</button>`).join(''):empty('Ancora nessun tap','Invia un tap a qualcuno nella griglia per farti notare.')}<button class="textlink" onclick="P.reloadTaps()">Aggiorna tap</button></section>`;}
P.tapTab=direction=>{A.direction=direction;renderTaps();};P.reloadTaps=()=>loadTaps().catch(e=>P.toast(e.message));
P.tap=async id=>{try{const result=await api('POST','/v1/taps/'+id);A.taps.sent=A.taps.sent.filter(p=>p.user_id!==id);A.taps.sent.unshift({...A.profiles.get(id),sent_at:result.sent_at});if(A.route?.id===id)renderProfile(A.profiles.get(id));P.toast('Tap inviato');}catch(error){P.toast(error.message);}};
async function loadChats(){const epoch=A.epoch;const data=await api('GET','/v1/chats');if(epoch!==A.epoch)return;const rows=(data.chats||[]).filter(p=>uid(p.user_id)&&uid(p.id));const changed=JSON.stringify(rows)!==JSON.stringify(A.chats);A.chats=rows;A.chats.forEach(cache);if(changed&&A.tab==='chat')renderChats();}
function renderChats(){if(A.tab!=='chat')return;const opened=new Set([...document.querySelectorAll('.swipe-row.open')].map(el=>el.dataset.chat));document.querySelector('#app').innerHTML=`<section class="real-page"><p class="eyebrow">LE TUE CONNESSIONI</p><h1>Chat</h1><p class="intro">Le conversazioni, dalla più recente.</p>${A.chats.length?A.chats.map(p=>`<div class="swipe-row ${opened.has(p.id)?'open':''}" data-chat="${p.id}"><button class="delete-swipe" aria-label="Elimina chat con ${esc(p.name)}" onclick="P.deletePrompt('${p.id}')">${icon('trash')}</button><button class="person-row swipe-content" onclick="if(!this.parentNode.dataset.swiped)P.chat('${p.user_id}')">${avatar()}<span class="copy"><span class="row"><b>${esc(p.name)}</b><time>${when(p.created_at)}</time></span><small>${esc(p.last_message)}</small></span></button></div>`).join(''):empty('Un ciao può bastare','Apri un profilo vicino a te e tocca Messaggio.','<button class="primary" onclick="P.show(\'near\')">Esplora i profili</button>')}<button class="textlink" onclick="P.reloadChats()">Aggiorna chat</button></section>`;bindSwipe();}
P.reloadChats=()=>loadChats().catch(e=>P.toast(e.message));
function bindSwipe(){document.querySelectorAll('.swipe-row').forEach(row=>{let start;row.addEventListener('pointerdown',e=>{if(e.target.closest('.delete-swipe'))return;start={x:e.clientX,y:e.clientY,drag:false};});row.addEventListener('pointermove',e=>{if(!start)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;if(Math.abs(dy)>12&&Math.abs(dy)>Math.abs(dx)){start=null;return;}if(Math.abs(dx)>20){start.drag=true;row.dataset.swiped='true';row.classList.toggle('open',dx<0);if(e.cancelable)e.preventDefault();}});row.addEventListener('pointerup',()=>{if(start?.drag)setTimeout(()=>delete row.dataset.swiped,350);start=null;});row.addEventListener('pointercancel',()=>{start=null;delete row.dataset.swiped;});});}
P.deletePrompt=conversation=>modal(`<h1>Eliminare la chat?</h1><p>La conversazione viene rimossa dalla tua lista. Il destinatario conserva i propri messaggi.</p><button class="primary wide" onclick="P.deleteChat('${conversation}')">Elimina chat</button>`);
P.deleteChat=async conversation=>{try{await api('DELETE','/v1/chats/'+conversation);const chat=A.chats.find(c=>c.id===conversation);if(chat){A.messages.delete(chat.user_id);A.cursors.delete(chat.user_id);A.drafts.delete(chat.user_id);}A.chats=A.chats.filter(c=>c.id!==conversation);P.closeModal();await P.show('chat');P.toast('Chat eliminata');}catch(error){P.toast(error.message);}};
P.chat=async id=>{if(!uid(id))return;A.route={type:'chat',id,conversation:A.chats.find(c=>c.user_id===id)?.id||null};if(!A.profiles.has(id))try{cache(await api('GET','/v1/profiles/'+id));}catch(e){P.toast(e.message);return P.back();}drawChat();try{await loadChats();if(A.route?.type==='chat'&&A.route.id===id){A.route.conversation=A.chats.find(c=>c.user_id===id)?.id||null;await loadMessages();}}catch(error){P.toast(error.message);}};
function drawChat(){if(A.route?.type!=='chat')return;const id=A.route.id,p=A.profiles.get(id)||{name:'Profilo'},messages=A.messages.get(id)||[];layer(`<div class="real-chat-head"><button class="round" aria-label="Indietro" onclick="P.back()">${icon('back')}</button><button class="chat-person" onclick="P.openProfile('${id}',true)">${avatar()}<span><b>${esc(p.name)}</b><small>Apri il profilo</small></span></button><button class="round" aria-label="Blocca profilo" onclick="P.confirmBlock('${id}')">${icon('block')}</button></div><div id="chat-messages" class="real-messages">${messages.length?messageMarkup(messages):empty('Inizia con un ciao','Scrivi il primo messaggio.')}</div><div id="emoji" class="real-emoji" hidden>${['😀','😍','😘','🔥','😂','😉','👍','🥰','👋','😈','😮','❤️'].map(value=>`<button onclick="P.emoji('${value}')">${value}</button>`).join('')}</div><form class="real-composer" onsubmit="P.send(event)"><button type="button" class="emoji-button" aria-label="Emoji" onclick="document.querySelector('#emoji').hidden=!document.querySelector('#emoji').hidden">${icon('smile')}</button><input id="message" aria-label="Messaggio" maxlength="4000" placeholder="Messaggio…" value="${esc(A.drafts.get(id)||'')}" oninput="P.draft(this.value)"><button class="real-send" id="message-send" aria-label="Invia messaggio">${icon('send')}</button></form>`,'real-chat');document.querySelector('#chat-messages').scrollTop=999999;}
function messageMarkup(rows){return rows.map(m=>`<article class="real-bubble ${m.sender===A.me.user_id?'outgoing':'incoming'}"><p>${esc(m.body)}</p><small>${when(m.created_at)}${m.sender===A.me.user_id?' · Inviato':''}</small></article>`).join('');}
function updateMessages(){if(A.route?.type!=='chat')return;const box=document.querySelector('#chat-messages');if(!box)return;const atEnd=box.scrollHeight-box.scrollTop-box.clientHeight<80,scroll=box.scrollTop;box.innerHTML=messageMarkup(A.messages.get(A.route.id)||[])||empty('Inizia con un ciao','Scrivi il primo messaggio.');box.scrollTop=atEnd?box.scrollHeight:scroll;}
async function loadMessages(){const route=A.route;if(route?.type!=='chat'||!route.conversation||route.loading)return;route.loading=true;const epoch=A.epoch;try{for(let page=0;page<20;page++){const after=A.cursors.get(route.id)||0,data=await api('GET',`/v1/chats/${route.conversation}/messages?after=${after}&limit=200`);if(epoch!==A.epoch||A.route!==route)return;const current=new Map((A.messages.get(route.id)||[]).map(m=>[m.id,m]));for(const m of data.messages||[])current.set(m.id,m);A.messages.set(route.id,[...current.values()].sort((a,b)=>a.id-b.id));A.cursors.set(route.id,data.next_after||after);updateMessages();if((data.messages||[]).length<200)break;}}finally{route.loading=false;}}
P.draft=text=>{if(A.route?.type==='chat')A.drafts.set(A.route.id,text);};
P.emoji=value=>{const input=document.querySelector('#message'),start=input.selectionStart??input.value.length,end=input.selectionEnd??start;input.value=input.value.slice(0,start)+value+input.value.slice(end);P.draft(input.value);input.focus();input.setSelectionRange(start+value.length,start+value.length);};
P.send=async event=>{event.preventDefault();const route=A.route,input=document.querySelector('#message'),button=document.querySelector('#message-send');if(route?.type!=='chat'||route.sending)return;const text=input.value.trim();if(!text)return;route.sending=true;button.disabled=true;let retry=A.retry.get(route.id);if(!retry||retry.text!==text){retry={text,client_id:crypto.randomUUID()};A.retry.set(route.id,retry);}const epoch=A.epoch;try{const result=await api('POST',`/v1/chats/${route.id}/messages`,retry);if(epoch!==A.epoch)return;route.conversation=result.conversation_id;const rows=A.messages.get(route.id)||[];if(!rows.some(m=>m.id===result.id))A.messages.set(route.id,[...rows,result].sort((a,b)=>a.id-b.id));A.retry.delete(route.id);if(A.route===route){if(input.value.trim()===text){input.value='';A.drafts.delete(route.id);}updateMessages();document.querySelector('#chat-messages').scrollTop=999999;}await loadChats();}catch(error){P.toast(error.message);}finally{route.sending=false;if(button.isConnected)button.disabled=false;}};
function renderMe(){const me=A.me;document.querySelector('#app').innerHTML=`<section class="real-page"><p class="eyebrow">IL TUO SPAZIO</p><h1>Il mio profilo</h1><div class="me-card">${avatar(true)}<h2>${esc(me.name)}</h2><p>${esc(me.bio||'Presentati, a modo tuo.')}</p><div class="me-actions"><button class="primary" onclick="P.edit()">${icon('edit')} Modifica</button><button class="round" aria-label="Come appare il mio profilo" onclick="P.preview()">${icon('user')}</button></div></div><button class="setting-row" onclick="P.preview()"><b>Come appare il mio profilo</b>${icon('user')}</button><button class="setting-row" onclick="P.privacy()"><b>Privacy e profili bloccati</b>${icon('lock')}</button><button class="setting-row" onclick="P.filter('favorites');P.show('near')"><b>Preferiti vicini</b>${icon('star')}</button><button class="setting-row" onclick="P.logout()"><b>Esci</b>${icon('exit')}</button><button class="textlink danger" onclick="P.deleteAccountPrompt()">Elimina il mio account</button><p class="hint">PRISM 0.11.0 · Anteprima online</p></section>`;}
P.preview=()=>{A.route={type:'preview'};const d=new Date(A.me.birth_date),now=new Date();let age=now.getFullYear()-d.getFullYear()-((now.getMonth()<d.getMonth()||(now.getMonth()===d.getMonth()&&now.getDate()<d.getDate()))?1:0);renderProfile({...A.me,age},true);};
P.edit=()=>{const me=A.me;A.route={type:'edit'};layer(`<div class="page-toolbar"><button class="round" aria-label="Indietro" onclick="P.back()">${icon('back')}</button><h1>Modifica profilo</h1></div><form class="real-editor" onsubmit="P.saveProfile(event)"><label>Nome<input id="edit-name" maxlength="40" value="${esc(me.name)}" required></label><label>Bio<textarea id="edit-bio" maxlength="1000">${esc(me.bio)}</textarea></label><fieldset><legend>Cerco · scegli più voci</legend>${['Chat','Amicizia','Appuntamenti','Relazione','Incontri'].map(v=>`<label class="option-check"><input type="checkbox" name="looking" value="${v}" ${(me.looking_for||[]).includes(v)?'checked':''}><span>${v}</span></label>`).join('')}</fieldset><label>Instagram<input id="edit-instagram" maxlength="100" value="${esc(me.instagram)}" placeholder="nomeutente"></label><label>Facebook<input id="edit-facebook" maxlength="100" value="${esc(me.facebook)}" placeholder="nomeutente"></label><p id="edit-status" role="status"></p><button class="primary wide" id="save-profile">Salva profilo</button></form>`,'real-editor-page');};
function profileBody(){const m=A.me;return {name:m.name,bio:m.bio,looking_for:m.looking_for||[],instagram:m.instagram||'',facebook:m.facebook||'',show_online:m.show_online,show_last_seen:m.show_last_seen,show_distance:m.show_distance};}
P.saveProfile=async event=>{event.preventDefault();const button=document.querySelector('#save-profile');button.disabled=true;try{A.me=await api('PUT','/v1/me',{...profileBody(),name:document.querySelector('#edit-name').value.trim(),bio:document.querySelector('#edit-bio').value,looking_for:[...document.querySelectorAll('[name=looking]:checked')].map(el=>el.value),instagram:document.querySelector('#edit-instagram').value.trim(),facebook:document.querySelector('#edit-facebook').value.trim()});P.back();renderMe();P.toast('Profilo aggiornato');}catch(error){document.querySelector('#edit-status').textContent=error.message;}finally{button.disabled=false;}};
P.privacy=async()=>{A.route={type:'privacy'};renderPrivacy();try{const data=await api('GET','/v1/blocks');A.blocked=(data.profiles||[]).filter(p=>uid(p.user_id));if(A.route?.type==='privacy')renderPrivacy();}catch(error){P.toast(error.message);}};
function renderPrivacy(){layer(`<div class="page-toolbar"><button class="round" aria-label="Indietro" onclick="P.back()">${icon('back')}</button><h1>Privacy e blocchi</h1></div><div class="real-privacy"><h2>Scegli cosa mostrare</h2>${[['show_online','Stato online'],['show_last_seen','Ultimo accesso'],['show_distance','Distanza']].map(([key,label])=>`<label class="privacy-toggle"><span>${label}</span><input type="checkbox" aria-label="${label}" ${A.me[key]?'checked':''} onchange="P.togglePrivacy('${key}',this)"></label>`).join('')}<h2>Profili bloccati · ${A.blocked.length}</h2><p class="hint">I profili bloccati e le chat restano nascosti finché non li sblocchi.</p>${A.blocked.length?A.blocked.map(p=>`<div class="blocked-row">${avatar()}<span class="copy"><b>${esc(p.name)}</b><small>Bloccato ${when(p.created_at)}</small></span><button class="pill" onclick="P.unblockPrompt('${p.user_id}')">Sblocca</button></div>`).join(''):'<p>Nessun profilo bloccato.</p>'}</div>`,'real-editor-page');}
P.togglePrivacy=async(key,input)=>{const previous=A.me[key];document.querySelectorAll('.privacy-toggle input').forEach(el=>el.disabled=true);try{A.me=await api('PUT','/v1/me',{...profileBody(),[key]:input.checked});P.toast('Privacy aggiornata');}catch(error){input.checked=previous;P.toast(error.message);}finally{document.querySelectorAll('.privacy-toggle input').forEach(el=>el.disabled=false);}};
P.unblockPrompt=id=>modal(`<h1>Sbloccare questo profilo?</h1><p>Il profilo potrà tornare visibile. La cronologia conservata tornerà accessibile.</p><button class="primary wide" onclick="P.unblock('${id}')">Sblocca</button>`);
P.unblock=async id=>{try{await api('DELETE','/v1/blocks/'+id);P.closeModal();await P.privacy();P.toast('Profilo sbloccato');}catch(error){P.toast(error.message);}};
P.logout=async()=>{try{await api('POST','/v1/auth/logout');clearAccount();P.auth('login');}catch(error){if(error.status===401){clearAccount();P.auth();}else P.toast(error.message);}};
P.deleteAccountPrompt=()=>modal(`<h1>Eliminare l’account?</h1><p>L’account, il profilo e le conversazioni saranno eliminati dal servizio. Conferma i dati per continuare.</p><form onsubmit="P.deleteAccount(event)"><label>Email<input id="delete-email" type="email" autocomplete="email" required></label><label>Password<input id="delete-password" type="password" autocomplete="current-password" minlength="12" maxlength="128" required></label><button class="primary wide">Elimina definitivamente</button></form>`);
P.deleteAccount=async event=>{event.preventDefault();const button=event.target.querySelector('button');button.disabled=true;try{await api('DELETE','/v1/me',{email:document.querySelector('#delete-email').value,password:document.querySelector('#delete-password').value});P.closeModal();clearAccount();P.auth('login','Account eliminato.');}catch(error){P.toast(error.message);}finally{button.disabled=false;}};
function renderExtra(){document.querySelector('#app').innerHTML=`<section class="real-page"><p class="eyebrow">PRISM EXTRA</p><h1>Più possibilità.<br>Prossimamente.</h1><div class="extra-hero">${icon('extra')}<h2>Il tuo piano è Free</h2><p>Gli abbonamenti saranno disponibili in un prossimo aggiornamento.</p></div><p class="hint">Nessun acquisto è attivo in questa anteprima.</p></section>`;}
async function heartbeat(){if(!A.me||document.hidden||window.prismForeground===false)return;try{await api('POST','/v1/me/heartbeat');A.lastHeartbeat=Date.now();}catch{}}
let polling=false;
async function poll(){if(!A.me||document.hidden||window.prismForeground===false||polling)return;polling=true;try{if(Date.now()-A.lastHeartbeat>60000)await heartbeat();if(A.route?.type==='chat'){await loadChats();const current=A.route;if(current?.type==='chat'){current.conversation=current.conversation||A.chats.find(c=>c.user_id===current.id)?.id;await loadMessages();}}else if(!A.route){if(A.tab==='chat')await loadChats();if(A.tab==='taps')await loadTaps();if(A.tab==='near'&&A.located)await loadNear();}}catch(error){if(error.status===404&&A.route?.type==='chat'){A.messages.delete(A.route.id);P.back();P.toast('Conversazione non disponibile');}}finally{polling=false;}}
window.prismResume=()=>{if(A.me)poll();};document.addEventListener('visibilitychange',()=>{if(!document.hidden)window.prismResume();});setInterval(poll,7000);
function viewport(){document.documentElement.style.setProperty('--viewport',(window.visualViewport?.height||window.innerHeight)+'px');}window.visualViewport?.addEventListener('resize',viewport);window.addEventListener('resize',viewport);viewport();
let pull=null;document.addEventListener('touchstart',e=>{if(A.me&&A.tab==='near'&&!A.route&&window.scrollY===0&&!A.loading)pull={x:e.touches[0].clientX,y:e.touches[0].clientY,dy:0};},{passive:true});document.addEventListener('touchmove',e=>{if(!pull)return;let dx=e.touches[0].clientX-pull.x,dy=e.touches[0].clientY-pull.y;if(Math.abs(dx)>35){pull=null;return;}pull.dy=dy;const hint=document.querySelector('#pull-hint');if(hint){hint.textContent=dy>80?'Rilascia per aggiornare':'Tira per aggiornare';hint.style.height=Math.min(Math.max(dy,0),70)+'px';}if(dy>0&&e.cancelable)e.preventDefault();},{passive:false});document.addEventListener('touchend',()=>{let yes=pull?.dy>80;pull=null;const hint=document.querySelector('#pull-hint');if(hint){hint.style.height='0px';hint.textContent='';}if(yes)P.refresh();});document.addEventListener('touchcancel',()=>{pull=null;const hint=document.querySelector('#pull-hint');if(hint){hint.style.height='0px';hint.textContent='';}});
(async()=>{try{await enter();}catch(error){P.auth('login',error.status===401?'':error.message);}finally{setTimeout(()=>document.querySelector('#boot')?.remove(),500);}})();
