'use strict';
const intent149={hello:'Un saluto',like:'Mi piaci',meet:'Incontriamoci'};let access149=[],privateRequest149=0,incomingBusy149=false,viewer149=null,callPrompt149=null;
function phone149(video=false){return video?'<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="6" width="12" height="12" rx="3"/><path d="m15 10 6-3v10l-6-3"/></svg>':'<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m5 3 4 1 1 5-3 2a14 14 0 0 0 6 6l2-3 5 1 1 4c0 2-2 3-4 2C9 19 5 15 3 7 2 5 3 3 5 3Z"/></svg>'}
function sheet149(title,html){closeSheet149();document.activeElement?.blur();const node=document.createElement('div');node.className='privatesheet149';node.setAttribute('role','dialog');node.setAttribute('aria-modal','true');node.innerHTML='<section><div class="grab149"></div><header><h2>'+esc(title)+'</h2><button onclick="closeSheet149()" aria-label="Chiudi">'+icon('close')+'</button></header>'+html+'</section>';node.addEventListener('click',e=>{if(e.target===node)closeSheet149()});document.body.append(node);node.querySelector('button')?.focus()}
function closeSheet149(){document.querySelector('.privatesheet149')?.remove()}
tapProfile5=function(id){const at=state.tapSentAt?.[id];if(at&&Date.now()-at<86400000)return toast('Puoi inviare un altro tap dopo 24 ore');sheet149('Un tap, la tua intenzione','<p>Come vuoi rompere il ghiaccio?</p><div class="intentlist149">'+Object.entries(intent149).map(([key,title])=>'<button onclick="sendIntent149('+Number(id)+',\''+key+'\')"><span>'+icon(key==='hello'?'bolt':key==='like'?'star':'location')+'</span><b>'+title+'</b>'+icon('next')+'</button>').join('')+'</div>')};tap=id=>tapProfile5(id);
async function sendIntent149(id,intent){const uid=people[id]?.user_id;if(!uid)return;const b=document.querySelectorAll('.intentlist149 button');b.forEach(x=>x.disabled=true);try{const r=await remote('POST','/v1/taps/'+uid,{intent});state.taps=[id,...state.taps.filter(x=>x!==id)];state.tapSentAt[id]=Date.parse(r.sent_at);closeSheet149();updateTapButton96(id);toast('Tap inviato · '+intent149[intent]);activityOnline().catch(e=>{O.syncError=e.message})}catch(e){toast(e.message);b.forEach(x=>x.disabled=false)}}
const renderIntent149=renderActivityOnline;renderActivityOnline=function(){renderIntent149();for(const tile of document.querySelectorAll('.activitytile124')){const row=historyState124().rows.find(r=>String(r.event_id)===tile.dataset.eventId);if(tapTab!=='views'&&row){const label=document.createElement('small');label.className='tapintent149';label.textContent=intent149[row.intent]||'Un saluto';tile.querySelector('.activitycaption124 b')?.after(label)}}};
const profileBase149=profile;profile=async function(id,fromChat=false){await profileBase149(id,fromChat);const page=document.querySelector('.profilepage:not(.ownpreview9)');if(!page||publicView99?.id!==id)return;const target=people[id]?.user_id;if(!target)return;const token=++privateRequest149;try{const data=await remote('GET','/v1/profiles/'+target+'/private-albums');if(token!==privateRequest149||!page.isConnected)return;const body=page.querySelector('.profilecontent,.profilecontent99,.profilebody99,.profilebody98')||page;const box=document.createElement('section');box.className='privateprofile149';box.dataset.target149=target;box.innerHTML=(data.albums.length?'<header><span>'+icon('lock')+'</span><div><h2>Album privati</h2><p>Chiedi accesso. La richiesta arriva in chat.</p></div></header><div class="privatealbums149">'+data.albums.map(a=>'<button data-album149="'+a.id+'" data-state149="'+(a.state||'locked')+'" onclick="privateAlbum149(\''+a.id+'\',\''+(a.state||'locked')+'\')"><span class="lockedcover149">'+icon(a.state==='granted'?'album':'lock')+'</span><b>'+esc(a.name)+'</b><small>'+a.photo_count+' foto · '+(a.state==='granted'?'Sbloccato':a.state==='pending'?'Richiesta inviata':'Richiedi accesso')+'</small></button>').join('')+'</div>':'');if(data.albums.length){const intro=body.querySelector('.profileintro99');if(intro)intro.before(box);else body.prepend(box)}}catch(e){if(page.isConnected){const note=document.createElement('p');note.className='privateunavailable150';note.setAttribute('role','status');note.textContent=e.message;(page.querySelector('.profilecontent,.profilecontent99,.profilebody99,.profilebody98')||page).append(note)}}};
async function privateAlbum149(id,status){if(status==='granted')return openPrivate149(id);if(status==='pending')return toast('Il proprietario deve ancora approvare la richiesta');sheet149('Foto private','<div class="permission149">'+icon('lock')+'<p>Le foto sono visibili solo con il consenso del proprietario. Può revocare l’accesso in qualsiasi momento.</p><p class="albumrequesterror154" role="alert" hidden></p><button type="button" class="primary" onclick="requestPrivate149(\''+id+'\')">Richiedi accesso</button></div>')}
async function requestPrivate149(id){const sheet=document.querySelector('.privatesheet149'),b=sheet?.querySelector('.permission149 button'),error=sheet?.querySelector('.albumrequesterror154');if(b?.disabled)return;if(b){b.disabled=true;b.textContent='Invio richiesta…'}if(error){error.hidden=true;error.textContent=''}try{const r=await remote('POST','/v1/private-albums/'+id+'/request',{});if(sheet?.isConnected)closeSheet149();toast(r.state==='granted'?'Accesso già approvato':'Richiesta inviata in chat');const card=document.querySelector('[data-album149="'+id+'"]');if(card){const status=r.state||'pending';card.dataset.state149=status;card.onclick=()=>privateAlbum149(id,status);const label=card.querySelector('small');if(label)label.textContent=label.textContent.split(' · ')[0]+' · '+(status==='granted'?'Sbloccato':'Richiesta inviata')}syncChatsOnline().catch(()=>{})}catch(e){if(error&&sheet?.isConnected){error.hidden=false;error.textContent=e.message||'Richiesta non inviata. Riprova.'}else toast(e.message);if(b){b.disabled=false;b.textContent='Riprova richiesta'}}}
async function openPrivate149(id){try{const data=await remote('GET','/v1/private-albums/'+id);viewer149={id,index:0,photos:data.photos,name:data.name};drawPrivate149()}catch(e){toast(e.message)}}
function drawPrivate149(){if(!viewer149)return;closeSheet149();const v=viewer149;sheet149(v.name,'<div class="privateviewer149"><img src="'+esc(v.photos[v.index])+'" alt="Foto privata '+(v.index+1)+'"><div><button onclick="movePrivate149(-1)" aria-label="Foto precedente">'+icon('back')+'</button><span>'+(v.index+1)+' / '+v.photos.length+'</span><button onclick="movePrivate149(1)" aria-label="Foto successiva">'+icon('next')+'</button></div></div>')}
function movePrivate149(d){if(viewer149){viewer149.index=(viewer149.index+d+viewer149.photos.length)%viewer149.photos.length;drawPrivate149()}}
const close149=closeSheet149;closeSheet149=function(){close149();if(!document.querySelector('.privateviewer149'))viewer149=null};
// Keep the protected viewer session while changing pictures.
const drawBase149=drawPrivate149;drawPrivate149=function(){const data=viewer149;close149();viewer149=data;if(!data)return;const v=data;sheet149(v.name,'<div class="privateviewer149"><img src="'+esc(v.photos[v.index])+'" alt="Foto privata"><div><button onclick="movePrivate149(-1)" aria-label="Foto precedente">'+icon('back')+'</button><span>'+(v.index+1)+' / '+v.photos.length+'</span><button onclick="movePrivate149(1)" aria-label="Foto successiva">'+icon('next')+'</button></div></div>');viewer149=data};
function decorateAlbums149(){const page=document.querySelector('.albumspage98');if(!page)return;const grid=page.querySelector('.albumgrid98');if(!grid)return;if(!page.querySelector('.albumpermissions149')){const el=document.createElement('div');el.className='albumpermissions149';el.innerHTML='<div><b>Condividi alle tue condizioni</b><p>Attiva il lucchetto per mostrare un album sul profilo. Approvi le richieste dalla chat.</p></div><button class="pill" onclick="albumAccess149()">'+icon('lock')+' Accessi</button>';grid.before(el)}for(const card of [...grid.querySelectorAll('.albumcard98')]){if(card.parentElement.classList.contains('albumwrap153'))continue;const aid=card.getAttribute('onclick')?.match(/editAlbum9\('([^']+)'/)?.[1];const a=state.albums.find(x=>x.id===aid);if(!a)continue;const wrap=document.createElement('article');wrap.className='albumwrap153';card.before(wrap);wrap.append(card);const label=document.createElement('label');label.className='albumvisibility153';label.innerHTML='<span>'+icon('lock')+'<b>Mostra sul profilo</b></span><input type="checkbox" aria-label="Mostra '+esc(a.name)+' come album privato sul profilo" '+(a.profile_visible?'checked':'')+'>';label.querySelector('input').onchange=e=>visibilityAlbum149(a.id,e.target);wrap.append(label)}}
const manager149=albumManager9;albumManager9=async function(){await manager149();decorateAlbums149()};const managerOriginal149=managerOriginalOnline;
async function visibilityAlbum149(id,input){input.disabled=true;try{await remote('PUT','/v1/me/albums/'+id+'/visibility',{visible:input.checked});const a=state.albums.find(a=>a.id===id);if(a)a.profile_visible=input.checked;toast(input.checked?'Album privato visibile sul profilo':'Album nascosto e accessi revocati')}catch(e){input.checked=!input.checked;toast(e.message)}finally{input.disabled=false}}
async function albumAccess149(){try{const r=await remote('GET','/v1/me/album-access');access149=r.requests;sheet149('Richieste e accessi','<div class="accesslist149">'+(r.requests.length?r.requests.map(a=>'<article><div><b>'+esc(a.requester_name)+'</b><p>'+esc(a.name)+'</p><small>'+(a.state==='pending'?'In attesa':a.state==='granted'?'Accesso attivo':'Accesso negato o revocato')+'</small></div>'+(a.state==='pending'?'<button onclick="grantAlbum149(\''+a.album_id+'\',\''+a.recipient+'\',true)">Approva</button>':'')+(a.state!=='rejected'?'<button onclick="grantAlbum149(\''+a.album_id+'\',\''+a.recipient+'\',false)">'+(a.state==='granted'?'Revoca':'Rifiuta')+'</button>':'')+'</article>').join(''):'<p>Non ci sono ancora richieste.</p>')+'</div>')}catch(e){toast(e.message)}}
async function grantAlbum149(id,recipient,granted){try{await remote('PUT','/v1/me/album-access/'+id+'/'+recipient,{granted});await albumAccess149();toast(granted?'Accesso approvato':'Accesso revocato')}catch(e){toast(e.message)}}
const me149=renderMe;renderMe=function(){me149();const button=document.querySelector('.mytile98.album98');if(button){button.querySelector('.copy small').textContent='Condivisione in chat e accessi privati';button.classList.add('ownalbums153')}};
const polish149=polishMessages120;polishMessages120=function(){polish149();const head=document.querySelector('.chatpage .conversationhead');if(!head||head.querySelector('.callbuttons149'))return;const id=Number(head.closest('.chatpage').dataset.chatId97);const el=document.createElement('div');el.className='callbuttons149';el.innerHTML='<button onclick="startCall149('+id+',\'audio\')" aria-label="Chiamata audio">'+phone149()+'</button><button onclick="startCall149('+id+',\'video\')" aria-label="Videochiamata">'+phone149(true)+'</button>';head.querySelector('.more126')?.before(el);head.querySelector('button[aria-label="Blocca profilo"]')?.remove()};
async function startCall149(id,mode){const user=people[id];if(!user?.user_id)return;sheet149(mode==='audio'?'Chiamata audio privata':'Videochiamata privata','<div class="permission149">'+phone149(mode==='video')+'<p>Chiama '+esc(user.name)+'. '+(extra101()?'Il tuo piano EXTRA non pone limiti di durata.':'Con Free la chiamata dura 60 secondi dal collegamento di entrambi.')+'</p><button class="primary" onclick="confirmCall149('+id+',\''+mode+'\')">Chiama</button></div>')}
async function confirmCall149(id,mode){const b=document.querySelector('.permission149 button');if(b)b.disabled=true;try{sessionStorage.setItem('callReturn153',people[id].user_id);const r=await remote('POST','/v1/calls',{target:people[id].user_id,mode});closeSheet149();await enterCall153(r.id)}catch(e){toast(e.message);if(b)b.disabled=false}}
function incoming149(row){if(callPrompt149===row.id)return;callPrompt149=row.id;document.querySelector('.incomingcall149')?.remove();const el=document.createElement('div');el.className='incomingcall149';el.setAttribute('role','alertdialog');el.setAttribute('aria-modal','true');el.innerHTML='<section><span>'+phone149(row.mode==='video')+'</span><p>'+(row.mode==='video'?'VIDEOCHIAMATA PRIVATA':'CHIAMATA AUDIO PRIVATA')+'</p><h2>'+esc(row.name)+'</h2><small>'+(row.limit_seconds===60?'Durata massima: 60 secondi':'Senza limite di durata')+'</small><div><button class="decline149" onclick="answerCall149(\''+row.id+'\',false)">Rifiuta</button><button class="primary" onclick="answerCall149(\''+row.id+'\',true)">Rispondi</button></div><p class="callanswererror149" role="alert"></p></section>';document.body.append(el);try{noticeSoundOnline()}catch{}}
async function answerCall149(id,accept){const b=[...document.querySelectorAll('.incomingcall149 button')];b.forEach(x=>x.disabled=true);try{const call=await remote('POST','/v1/calls/'+id+(accept?'/accept':'/end'));if(accept)sessionStorage.setItem('callReturn153',call.caller);document.querySelector('.incomingcall149')?.remove();callPrompt149=null;if(accept)await enterCall153(id)}catch(e){const error=document.querySelector('.callanswererror149');if(error)error.textContent=e.message;b.forEach(x=>x.disabled=false)}}
async function pollPrivate149(){if(incomingBusy149||!window.signedIn||!O.me||document.hidden||window.prismForeground===false||window.prismMaintenance147)return;incomingBusy149=true;const epoch=O.epoch;try{const r=await remote('GET','/v1/calls');if(epoch!==O.epoch)return;const row=r.calls.find(x=>!x.outgoing&&x.status==='ringing');if(row)incoming149(row);else{document.querySelector('.incomingcall149')?.remove();callPrompt149=null}if(viewer149){const id=viewer149.id;try{await remote('GET','/v1/private-albums/'+id+'/access')}catch(e){if(e.status===403||e.status===404){closeSheet149();toast('L’accesso a questo album è stato revocato')}}}}catch{}finally{incomingBusy149=false}}
window.prismCallPush149=async pending=>{await pollPrivate149();const id=pending.event?.split(':')[1];if(id&&!callPrompt149)toast('La chiamata è già conclusa')};
const plan149=planPage101;planPage101=function(){plan149();const list=document.querySelector('.extrafeatures120');if(list&&!list.querySelector('.callfeature149'))list.insertAdjacentHTML('beforeend','<article class="callfeature149">'+phone149(true)+'<div><h3>Chiamate e videochiamate private</h3><p>Free: 60 secondi per chiamata avviata</p></div><strong>Senza limite</strong></article>')};
let requestsSnapshot149=null,privateSyncAt149=0;
async function syncAccess149(){if(!O.me||document.hidden||window.prismForeground===false||Date.now()-privateSyncAt149<10000)return;privateSyncAt149=Date.now();const epoch=O.epoch;try{const r=await remote('GET','/v1/me/album-access');if(epoch!==O.epoch)return;const pending=r.requests.filter(a=>a.state==='pending');const snapshot=pending.map(a=>a.album_id+':'+a.recipient).join('|');if(requestsSnapshot149!==null&&snapshot!==requestsSnapshot149&&pending.length)toast('Nuova richiesta per le tue foto private');requestsSnapshot149=snapshot;const own=document.querySelector('.privateinbox149 small');if(own)own.textContent=pending.length?pending.length+' richieste da approvare':'Album, richieste e accessi';const page=document.querySelector('.privateprofile149');if(page){const data=await remote('GET','/v1/profiles/'+page.dataset.target149+'/private-albums');if(epoch!==O.epoch||!page.isConnected)return;for(const button of page.querySelectorAll('[data-album149]')){const a=data.albums.find(a=>a.id===button.dataset.album149);if(!a){button.remove();continue}const status=a.state||'locked';button.dataset.state149=status;button.onclick=()=>privateAlbum149(a.id,status);button.querySelector('small').textContent=a.photo_count+' foto · '+(status==='granted'?'Sbloccato':status==='pending'?'Richiesta inviata':'Richiedi accesso');button.querySelector('.lockedcover149').innerHTML=icon(status==='granted'?'album':'lock')}}}catch{}}
setInterval(syncAccess149,3000);
const reset149=resetOnline;resetOnline=function(){requestsSnapshot149=null;privateSyncAt149=0;privateRequest149++;callPrompt149=null;closeSheet149();document.querySelector('.incomingcall149')?.remove();reset149()};
const back149=window.prismBack;window.prismBack=function(){if(document.querySelector('.privatesheet149'))return closeSheet149();back149()};
new MutationObserver(()=>{decorateAlbums149()}).observe(document.body,{childList:true,subtree:true});
setInterval(pollPrivate149,3000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)pollPrivate149()});setTimeout(pollPrivate149,500);

const options149=chatOptions126;chatOptions126=function(id,b){options149(id,b);const menu=document.querySelector('.chatoptions126');if(menu&&!menu.querySelector('.block149')){const block=document.createElement('button');block.className='block149';block.innerHTML=icon('block')+' Blocca profilo';block.onclick=()=>confirmBlock(id);menu.append(block)}};
