'use strict';
async function enterCall153(id){if(!/^[a-f0-9-]{36}$/i.test(id))throw Error('Chiamata non valida');let result;if(window.PrismIOS)result=await bridge('callOpen',{room:id});else if(window.PrismNative?.callOpen)result=await new Promise(resolve=>{const key='callopen'+Date.now();callbacks.set(key,{resolve,timer:setTimeout(()=>{callbacks.delete(key);resolve({status:0})},10000)});PrismNative.callOpen(key,id)});else throw Error('Aggiorna PRISM per usare le chiamate private.');if(result?.status!==200)throw Error('Impossibile aprire la chiamata. Riprova.')}
const message153=messageHTML;messageHTML=function(m,id,index){if(m?.type!=='albumAccess')return message153(m,id,index);const owner=String(m.owner)===String(O.me?.user_id),pending=m.state==='pending',granted=m.state==='granted';return '<div class="albumrequest153"><header><span>'+icon('lock')+'</span><div><small>ALBUM PRIVATO</small><b>'+esc(m.name||'Foto private')+'</b></div></header><p>'+ (pending?(owner?'Ti ha chiesto di vedere questo album.':'Hai richiesto l’accesso a questo album.'):granted?'Accesso approvato.':'Accesso rifiutato o revocato.')+'</p><div class="albumrequestactions153">'+(owner&&pending?'<button type="button" class="primary" onclick="chatGrant153(\''+m.album_id+'\',\''+m.recipient+'\',true,this)">Approva</button><button type="button" onclick="chatGrant153(\''+m.album_id+'\',\''+m.recipient+'\',false,this)">Rifiuta</button>':granted?(owner?'<button type="button" onclick="chatGrant153(\''+m.album_id+'\',\''+m.recipient+'\',false,this)">Revoca accesso</button>':'<button type="button" class="primary" onclick="openPrivate149(\''+m.album_id+'\')">'+icon('album')+' Apri album</button>'):'<span>'+icon(pending?'clock':'lock')+(pending?'In attesa di approvazione':'Foto protette')+'</span>')+'</div></div>'};
const label153=messageLabel;messageLabel=function(m){return m?.type==='albumAccess'?(m.state==='pending'?'Richiesta album privato':m.state==='granted'?'Album privato sbloccato':'Accesso album revocato'):label153(m)};
async function chatGrant153(aid,recipient,granted,button){const card=button.closest('.albumrequest153');card.querySelectorAll('button').forEach(b=>b.disabled=true);try{await remote('PUT','/v1/me/album-access/'+aid+'/'+recipient,{granted});for(const list of Object.values(state.messages))for(const m of list)if(m.type==='albumAccess'&&m.album_id===aid&&m.recipient===recipient)m.state=granted?'granted':'rejected';if(O.pageChat!==null)renderCurrentMessagesOnline(O.pageChat);syncChatsOnline().catch(()=>{});toast(granted?'Accesso approvato':'Accesso revocato')}catch(e){toast(e.message);card.querySelectorAll('button').forEach(b=>b.disabled=false)}}
let returnTries153=0;const returnTimer153=setInterval(()=>{const uid=sessionStorage.getItem('callReturn153');if(!uid||++returnTries153>40){clearInterval(returnTimer153);return}if(!window.signedIn||!O.me)return;const p=people.find(x=>x?.user_id===uid);if(p){sessionStorage.removeItem('callReturn153');clearInterval(returnTimer153);chat(p.id)}},500);

const history155=messageHTML;messageHTML=function(m,id,index){if(m?.type!=='privateCall')return history155(m,id,index);const outgoing=m.outgoing103===true||m.direction==='outgoing',video=m.mode==='video',title=video?'Videochiamata':'Chiamata audio',outcome=m.outcome==='received'?(outgoing?'effettuata':'ricevuta'):m.outcome==='failed'?'non riuscita':outgoing?'senza risposta':'persa',seconds=Math.max(0,Number(m.duration_seconds)||0),duration=Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0');return '<div class="callhistory155 '+(m.outcome==='missed'?'missed155':'')+'"><span>'+phone149(video)+'</span><div><b>'+title+' '+outcome+'</b><small>'+(m.outcome==='received'?duration+' · Chiamata privata':m.outcome==='failed'?'Il collegamento non è riuscito':'Nessuna conversazione avviata')+'</small></div></div>'};
const historyLabel155=messageLabel;messageLabel=function(m){if(m?.type!=='privateCall')return historyLabel155(m);return(m.mode==='video'?'Videochiamata':'Chiamata audio')+(m.outcome==='received'?' ricevuta':m.outcome==='failed'?' non riuscita':' persa')};
