'use strict';
const O=window.PRISMOnline={me:null,near:new Set(),chats:[],stories:[],ids:new Map(),pendingEmail:'',verifyPassword:'',epoch:0,polling:false,sendTasks:new Map(),pageChat:null,revision:0,albumRevision:0,favoritePending:new Set(),notifications:null,seenNotices:new Set(),readTasks:new Set()};
const callbacks=new Map();
window.prismNativeReply=(id,result)=>{const task=callbacks.get(id);if(task){clearTimeout(task.timer);callbacks.delete(id);task.resolve(result)}};
function bridge(action,args={}){if(window.PrismIOS)return PrismIOS.call(action,args);if(window.PrismNative)return new Promise(resolve=>{const id='r'+Date.now().toString(36)+Math.random().toString(36).slice(2);callbacks.set(id,{resolve,timer:setTimeout(()=>{callbacks.delete(id);resolve({status:0,data:{detail:'Connessione lenta. Riprova.'}})},35000)});if(action==='api')PrismNative.request(id,args.method,args.path,args.body||'');else if(action==='locate')PrismNative.locate(id);else{PrismNative.settings();prismNativeReply(id,{status:200,data:{}})}});return Promise.resolve({status:0,data:{detail:'Apri PRISM dall’app installata.'}})}
async function remote(method,path,data){let response;try{response=await bridge('api',{method,path,body:data===undefined?'':JSON.stringify(data)})}catch{throw Error('Connessione non disponibile. Riprova.')}if(response.status>=200&&response.status<300)return response.data||{};let e=Error(typeof response.data?.detail==='string'?response.data.detail:response.status===404?'Aggiorna il backend PRISM 0.3.1 prima di usare questa versione.':response.status===429?'Attendi un minuto e riprova.':'Controlla i dati inseriti.');e.status=response.status;if(e.status===401&&!path.startsWith('/v1/auth/')){resetOnline();auth('login')}throw e}
function resetOnline(){O.epoch++;O.notifications=null;O.seenNotices.clear();O.readTasks.clear();O.favoritePending.clear();O.revision++;O.me=null;O.chats=[];O.stories=[];O.ids.clear();O.near.clear();O.pageChat=null;O.sendTasks.clear();people.splice(0);state={favorites:[],blocked:[],messages:{},stories:[],taps:[],receivedTaps:[],tapSentAt:{},tapReceivedAt102:{},profileVisits102:[],storySeen:{},photos:[],photo:'p0.svg',albums:[],name:'Il mio profilo',bio:'',radiusKm:5,privacy:{online:true,distance:true,lastSeen:true},intents:[],demoPlan101:'free',chatActivity:{},chatDrafts:{},chatDraftAt:{}};window.signedIn=false;closeOverlay();}
save=function(){return true}; // Server actions below commit explicitly; drafts remain in memory.
function person(row){if(!row.user_id)return null;let id=O.ids.get(row.user_id);if(id===undefined){id=people.length;O.ids.set(row.user_id,id);people.push({id,user_id:row.user_id,name:'',age:'',distance:Infinity,photo:null,photos:[],online:false,interest:''})}let p=people[id],extra=row.extra||{};Object.assign(p,row,{id});if('extra' in row){Object.assign(p,extra);p.photos=extra.photos||p.photos}if('photo' in row)p.photo=row.photo;if(p.photos?.length)p.photo=p.photos[0];if('distance_m' in row){p.distance=row.distance_m??0;p.distanceHidden=row.distance_m==null}p.interest=p.tribe||'';if(!O.favoritePending.has(id)&&row.favorite===true&&!state.favorites.includes(id))state.favorites.push(id);if(!O.favoritePending.has(id)&&row.favorite===false)state.favorites=state.favorites.filter(v=>v!==id);return id}
function myProfile(row){O.me=row;const birth=new Date(row.birth_date),now=new Date();const age=now.getFullYear()-birth.getFullYear()-((now.getMonth()<birth.getMonth()||(now.getMonth()===birth.getMonth()&&now.getDate()<birth.getDate()))?1:0);Object.assign(state,row.extra||{},{name:row.name,bio:row.bio,age,intents:row.looking_for||[],intent:(row.looking_for||[]).join(' · '),instagram:row.instagram||'',facebook:row.facebook||'',photos:row.extra?.photos||[],photo:row.extra?.photos?.[0]||'p0.svg',privacy:{online:row.show_online,distance:row.show_distance,lastSeen:row.show_last_seen},demoPlan101:'free'});}
function profileBody(p=state){return {name:p.name,bio:p.bio||'',looking_for:p.intents||[],instagram:p.instagram||'',facebook:p.facebook||'',show_online:state.privacy.online,show_distance:state.privacy.distance,show_last_seen:state.privacy.lastSeen}}
const oldAuthOnline=auth;
auth=function(mode='login'){document.body.classList.remove('nearview100');O.pageChat=null;oldAuthOnline(mode);document.querySelector('.authdemo95')?.remove();const info=document.querySelector('.authprivacy95 span');if(info)info.textContent='PRISM 0.11.2 · Account protetto con verifica email.';document.querySelectorAll('#password,#confirm').forEach(el=>{el.minLength=12;el.placeholder=el.id==='confirm'?'Ripeti la password':'Almeno 12 caratteri'});if(mode==='register'){let box=document.createElement('div');box.innerHTML='<label for="birth_date">Data di nascita</label><div class="authfield95"><input id="birth_date" type="date" required autocomplete="bday"></div>';document.querySelector('.authcheck95').before(box);document.querySelector('.authcheck95 span').textContent='Confermo di avere almeno 18 anni.'}else{let buttons=document.createElement('div');buttons.innerHTML='<button class="authdemo95" onclick="forgotOnline()">Password dimenticata?</button><button class="authdemo95" onclick="verifyOnline()">Inserisci il codice di verifica</button>';document.querySelector('.authform95').after(buttons)}};
authenticate=async function(event,register){event.preventDefault();const email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value,button=document.querySelector('#authsubmit95'),error=document.querySelector('#autherror');if(register&&password!==document.querySelector('#confirm').value){error.textContent='Le password non coincidono.';return}button.disabled=true;O.pendingEmail=email;authDraft95.email=email;try{if(register){await remote('POST','/v1/auth/register',{email,password,name:document.querySelector('#authname').value.trim(),birth_date:document.querySelector('#birth_date').value,adult_confirmed:document.querySelector('#adult').checked});O.verifyPassword=password;verifyOnline('Ti abbiamo inviato un codice. Controlla anche lo spam.')}else{await remote('POST','/v1/auth/login',{email,password});await enterOnline()}}catch(e){error.textContent=e.message;if(e.status===403){O.verifyPassword=password;verifyOnline(e.message)}}finally{button.disabled=false}};
function verifyOnline(notice=''){window.signedIn=false;document.querySelector('header').style.display='none';document.querySelector('.notice').style.display='none';document.querySelector('#nav').style.display='none';document.querySelector('#app').innerHTML=`<section class="auth95"><div class="authbrand95"><img src="prism-mark.svg" alt="">PRISM</div><div class="authintro95"><h1>Verifica la<br>tua email.</h1><p>Inserisci il codice di sei cifre ricevuto.<br>Scade dopo dieci minuti.</p></div><form class="authform95" onsubmit="submitCodeOnline(event)"><label>Email</label><div class="authfield95">${icon('mail')}<input id="verify_email" type="email" required value="${esc(O.pendingEmail||authDraft95.email||'')}"></div><label>Codice di verifica</label><div class="authfield95">${icon('lock')}<input id="verify_code" type="text" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" required placeholder="000000" style="letter-spacing:.35em;font-size:24px"></div><p id="code_status" class="autherror" role="status">${esc(notice)}</p><button class="authsubmit95">Verifica email ${icon('chevron')}</button></form><button class="authdemo95" id="resend_code" onclick="resendCodeOnline()">Invia un nuovo codice</button><button class="authdemo95" onclick="auth('login')">Torna al login</button></section>`;}
async function submitCodeOnline(e){e.preventDefault();let button=e.target.querySelector('button');button.disabled=true;try{const email=document.querySelector('#verify_email').value.trim();await remote('POST','/v1/auth/verify-code',{email,code:document.querySelector('#verify_code').value.trim()});O.pendingEmail=email;authDraft95.email=email;const password=O.verifyPassword;O.verifyPassword='';if(password){await remote('POST','/v1/auth/login',{email,password});await enterOnline()}else{auth('login');toast('Email verificata. Ora accedi.')}}catch(error){document.querySelector('#code_status')?.replaceChildren(document.createTextNode(error.message))}finally{button.disabled=false}}
async function resendCodeOnline(){const button=document.querySelector('#resend_code');button.disabled=true;try{await remote('POST','/v1/auth/resend-verification',{email:document.querySelector('#verify_email').value.trim()});document.querySelector('#code_status').textContent='Se possibile, riceverai un nuovo codice. Puoi richiederlo ogni 60 secondi.';setTimeout(()=>{if(button.isConnected)button.disabled=false},60000)}catch(e){document.querySelector('#code_status').textContent=e.message;button.disabled=false}}
function forgotOnline(){overlay(`<h1>Password dimenticata?</h1><p>Riceverai un link per scegliere una nuova password.</p><form onsubmit="submitForgotOnline(event)"><label>Email<input id="forgot_email" type="email" required value="${esc(O.pendingEmail||'')}"></label><p id="forgot_status"></p><button class="primary wide">Invia email</button></form>`)}
async function submitForgotOnline(e){e.preventDefault();let b=e.target.querySelector('button');b.disabled=true;try{await remote('POST','/v1/auth/forgot-password',{email:document.querySelector('#forgot_email').value});document.querySelector('#forgot_status').textContent='Se possibile, riceverai un’email con le istruzioni.'}catch(error){document.querySelector('#forgot_status').textContent=error.message}finally{b.disabled=false}}
async function enterOnline(){const me=await remote('GET','/v1/me');resetOnline();myProfile(me);window.signedIn=true;show('near');await syncOnline();if(O.me.latitude!=null)await nearbyOnline();}
const showOriginalOnline=show;
show=function(t){O.pageChat=null;showOriginalOnline(t);if(window.signedIn){if(t==='chat')syncChatsOnline().catch(e=>toast(e.message));if(t==='taps')activityOnline().catch(e=>toast(e.message));if(t==='likes')nearbyOnline('favorites').catch(e=>toast(e.message));polishOnline();drawNoticesOnline()}};
function polishOnline(){document.querySelector('.notice').style.display='none';document.querySelector('.activitydemo102')?.remove();document.querySelector('.plandemo101')?.remove();const price=document.querySelector('.planhero101 .pricehint103');if(price&&price.textContent!=='Prezzo proposto · Acquisti non ancora attivi.')price.textContent='Prezzo proposto · Acquisti non ancora attivi.';let tagline=document.querySelector('.plantile101 b');if(tagline&&tagline.textContent!=='Free · PRISM EXTRA')tagline.textContent='Free · PRISM EXTRA';document.querySelectorAll('.privacydelete100').forEach(el=>{if(!el.dataset.fixed){el.dataset.fixed='true';el.innerHTML=icon('exit')+' Elimina account'}});const chatPage=document.querySelector('.chatpage');if(chatPage){const id=Number(chatPage.dataset.chatId97);chatPage.querySelectorAll('.bubble').forEach((el,i)=>{el.classList.toggle('incomingOnline',state.messages[id]?.[i]?.outgoing103===false)})}const details=document.querySelector('.privacydata100 p');if(details&&!details.dataset.fixed){details.dataset.fixed='true';details.innerHTML='<b>I tuoi dati</b><br>Account, profilo e contenuti vengono conservati sul server PRISM. Puoi eliminare il tuo account.';}}
const nearOriginalOnline=renderNearby100;
renderNearby100=function(){nearOriginalOnline();let label=document.querySelector('.nearheading100 p');if(label)label.textContent=O.me?.latitude!=null?O.near.size+' profili · entro '+state.radiusKm+' km':'Attiva la posizione per vedere chi è vicino';if(O.me?.latitude==null){const panel=document.createElement('div');panel.className='nearempty100';panel.innerHTML='<h2>Il prossimo ciao è vicino.</h2><p>Consenti la posizione del telefono.</p><button class="primary" onclick="refresh9()">Attiva posizione</button>';document.querySelector('.nearfilters100').after(panel)}};
nearbyCard100=function(p){const dist=p.distanceHidden?'Distanza nascosta':p.distance>=1000?(p.distance/1000).toFixed(1).replace('.',',')+' km':p.distance+' m';return `<button class="card" aria-label="Apri profilo di ${esc(p.name)}" onclick="profile(${p.id})"><img src="${esc(p.photo||'p0.svg')}" alt="">${state.favorites.includes(p.id)?`<span class="star">${icon('star')}</span>`:''}<div class="caption"><b>${p.online?'<i class="dot"></i>':''}${esc(p.name)}, ${p.age}</b><small>${dist}</small></div></button>`};
async function nearbyOnline(mode='all'){const epoch=O.epoch,revision=O.revision;const data=await remote('GET',`/v1/nearby?radius_km=${state.radiusKm}&mode=${mode}&limit=30`);if(epoch!==O.epoch)return;if(mode==='all'){O.near.clear();people.forEach(p=>p.distance=Infinity)}for(const row of data.profiles||[]){if(revision!==O.revision)delete row.favorite;const id=person(row);if(id!==null)O.near.add(id)}if(!document.querySelector('.overlay')&&(tab==='near'||tab==='likes')){showOriginalOnline(tab);polishOnline()}}
refresh9=async function(){if(refreshBusy9||!window.signedIn)return;refreshBusy9=true;try{const geo=await bridge('locate');if(geo.status!==200)throw Error(geo.data?.detail||'Posizione non disponibile');await remote('PUT','/v1/me/location',geo.data);Object.assign(O.me,geo.data);await nearbyOnline();await storiesOnline();updatedAt100=Date.now();toast('Profili e storie aggiornati')}catch(e){toast(e.message)}finally{refreshBusy9=false;resetPull100();if(tab==='near'&&!document.querySelector('.overlay')){showOriginalOnline('near');polishOnline()}}};
const filtersOriginalOnline=filters;filters=function(){filtersOriginalOnline();document.querySelector('#radiusinput').max=5;document.querySelector('#radiusinput').value=Math.min(state.radiusKm,5)};
applyRadius100=async function(){state.radiusKm=Math.min(5,Number(document.querySelector('#radiusinput').value));closeOverlay();show('near');if(O.me?.latitude!=null)try{await nearbyOnline();await storiesOnline()}catch(e){toast(e.message)}};
async function activityOnline(){const epoch=O.epoch;const [sent,received,visits]=await Promise.all([remote('GET','/v1/taps?direction=sent'),remote('GET','/v1/taps?direction=received'),remote('GET','/v1/visits')]);if(epoch!==O.epoch)return;for(const [key,rows,times]of [['taps',sent.taps,'tapSentAt'],['receivedTaps',received.taps,'tapReceivedAt102']]){state[key]=[];state[times]={};for(const row of rows||[]){const id=person(row);if(id!==null){state[key].push(id);state[times][id]=Date.parse(row.sent_at)}}}state.profileVisits102=[];for(const [index,row]of (visits.visits||[]).entries()){let id;if(row.locked){const key='locked-visit-'+index;id=O.ids.get(key);if(id===undefined){id=people.length;O.ids.set(key,id);people.push({id,name:'Profilo riservato',age:'',distance:0})}Object.assign(people[id],{photo:row.photo,distance:row.distance_m??0,distanceHidden:row.distance_m==null,locked:true})}else id=person(row);state.profileVisits102.push({id,time:Date.parse(row.seen_at),locked:row.locked})}if(tab==='taps'&&!document.querySelector('.overlay')){renderTaps();polishOnline()}}
const tapsOriginalOnline=renderTaps;renderTaps=function(){tapsOriginalOnline();let intro=document.querySelector('.activityintro102');if(intro)intro.innerHTML='Chi ti nota, chi ti cerca.';document.querySelector('.activitydemo102')?.remove();drawNoticesOnline();ackActivityOnline();};
tapProfile5=async function(id,fromChat=false){try{const result=await remote('POST','/v1/taps/'+people[id].user_id);state.taps=[id,...state.taps.filter(v=>v!==id)];state.tapSentAt[id]=Date.parse(result.sent_at);updateTapButton96(id);renderStateOnline();toast('Tap inviato')}catch(e){toast(e.message)}};tap=id=>tapProfile5(id);
function renderStateOnline(){if(!window.signedIn)return;const scroll=window.scrollY;showOriginalOnline(tab);window.scrollTo(0,scroll);polishOnline();drawNoticesOnline()}
favoritePublic99=async function(id){if(O.favoritePending.has(id))return;const yes=state.favorites.includes(id);O.favoritePending.add(id);O.revision++;state.favorites=yes?state.favorites.filter(v=>v!==id):[...state.favorites,id];people[id].favorite=!yes;const button=document.querySelector('#publicfavorite99');if(button){button.classList.toggle('favactive',!yes);button.setAttribute('aria-pressed',String(!yes));button.disabled=true}renderStateOnline();try{await remote(yes?'DELETE':'PUT','/v1/favorites/'+people[id].user_id);toast(yes?'Rimosso dai preferiti':'Aggiunto ai preferiti')}catch(e){state.favorites=yes?[...state.favorites.filter(v=>v!==id),id]:state.favorites.filter(v=>v!==id);people[id].favorite=yes;if(button?.isConnected){button.classList.toggle('favactive',yes);button.setAttribute('aria-pressed',String(yes))}renderStateOnline();toast('Salvataggio non riuscito: '+e.message)}finally{O.favoritePending.delete(id);O.revision++;if(button?.isConnected)button.disabled=false}};fav=favoritePublic99;
async function favoritesOnline(){const epoch=O.epoch,revision=O.revision,data=await remote('GET','/v1/favorites');if(epoch!==O.epoch||revision!==O.revision)return;const before=JSON.stringify(state.favorites);state.favorites=(data.profiles||[]).map(person).filter(v=>v!==null);if(before!==JSON.stringify(state.favorites))renderStateOnline()}

const profileDataOriginalOnline=profileData99;profileData99=function(id,own=false){if(own)return profileDataOriginalOnline(id,true);const p=people[id];return {...p,photos:p.photos?.length?p.photos:[p.photo||'p0.svg'],bio:p.bio||'Nessuna bio aggiunta.',looking:p.looking_for||[],details:[p.height?p.height+' cm':'',p.weight?p.weight+' kg':'',p.identity,p.position,p.relationship].filter(Boolean),interest:p.tribe||'',social:['instagram','facebook'].filter(k=>p[k]).map(k=>`<span class="socialtag11">${icon(k)} ${esc(p[k])}</span>`).join('')}};
const profileOriginalOnline=profile;profile=async function(id,fromChat=false){if(!people[id]||people[id].locked)return;O.pageChat=null;try{person(await remote('GET','/v1/profiles/'+people[id].user_id));profileOriginalOnline(id,fromChat);if(!O.stories.some(s=>s.user_id===people[id].user_id))document.querySelector('.storyprofilebutton')?.remove();profileActivityOnline(id);const loc=document.querySelector('.profilelocation99');if(loc)loc.textContent=people[id].distanceHidden||!Number.isFinite(people[id].distance)?'Distanza nascosta':(people[id].distance>=1000?(people[id].distance/1000).toFixed(1)+' km':people[id].distance+' m')+' da te'}catch(e){toast(e.message)}};
function profileActivityOnline(id){const p=people[id],tag=document.querySelector('.public99 .onlinetag'),last=document.querySelector('.lastseen104 span');if(tag)tag.textContent=p.online?'Online ora':'Offline';if(last)last.textContent=p.last_seen?lastSeenText104(Date.parse(p.last_seen)):'Ultimo accesso non disponibile'}
saveMe=async function(){captureDraft7();let draft=profileDraft7;if(!draft.name.trim())return toast('Inserisci il nome');const buttons=[...document.querySelectorAll('.editor98 button')];buttons.forEach(b=>b.disabled=true);try{const row=await remote('PUT','/v1/me',{...profileBody(draft),extra:{photos:draft.photos||[],height:String(draft.height||''),weight:String(draft.weight||''),identity:draft.identity||'',position:draft.position||'',tribe:draft.tribe||'',relationship:draft.relationship||''}});myProfile(row);profileDraft7=null;closeOverlay();show('me');toast('Profilo aggiornato')}catch(e){toast(e.message)}finally{buttons.forEach(b=>b.disabled=false)}};
const editorOriginalOnline=renderEditor7;renderEditor7=function(){editorOriginalOnline();const age=document.querySelector('#edit_age');if(age){age.readOnly=true;age.title='Età calcolata dalla data di nascita'}};
async function blockedOnline(){const epoch=O.epoch,data=await remote('GET','/v1/blocks');if(epoch!==O.epoch)return;state.blocked=(data.profiles||[]).map(person).filter(v=>v!==null)}
const privacyOriginalOnline=privacyPage;privacyPage=async function(){O.pageChat=null;try{await blockedOnline();privacyOriginalOnline();polishOnline()}catch(e){toast(e.message)}};
setPrivacy100=async function(key,input){const before=state.privacy[key];state.privacy[key]=input.checked;document.querySelectorAll('.privacyrow100 input').forEach(el=>el.disabled=true);try{myProfile(await remote('PUT','/v1/me',profileBody()));toast('Privacy aggiornata')}catch(e){state.privacy[key]=before;input.checked=before;toast(e.message)}finally{document.querySelectorAll('.privacyrow100 input').forEach(el=>el.disabled=false)}};
block=async function(id){try{await remote('PUT','/v1/blocks/'+people[id].user_id);state.blocked.push(id);O.near.delete(id);state.favorites=state.favorites.filter(v=>v!==id);state.taps=state.taps.filter(v=>v!==id);state.receivedTaps=state.receivedTaps.filter(v=>v!==id);state.profileVisits102=state.profileVisits102.filter(v=>v.id!==id);delete state.messages[id];delete state.chatDrafts[id];delete state.chatActivity[id];O.chats=O.chats.filter(c=>c.user_id!==people[id].user_id);O.stories=O.stories.filter(s=>s.user_id!==people[id].user_id);people[id].distance=Infinity;closeOverlay();show(tab);await notificationsOnline();toast('Profilo bloccato')}catch(e){toast(e.message)}};
unblock7=async function(id){try{await remote('DELETE','/v1/blocks/'+people[id].user_id);await privacyPage();toast('Profilo sbloccato')}catch(e){toast(e.message)}};
reportProfile6=function(id,fromChat){overlay(`<h1>Segnala ${esc(people[id].name)}</h1><p>Descrivi il problema.</p><form onsubmit="reportOnline(event,${id})"><label>Motivo<textarea id="report_reason" minlength="3" maxlength="1000" required></textarea></label><button class="primary wide">Invia segnalazione</button></form>`)};
async function reportOnline(e,id){e.preventDefault();try{await remote('POST','/v1/reports/'+people[id].user_id,{reason:document.querySelector('#report_reason').value});toast('Segnalazione inviata');closeOverlay()}catch(error){toast(error.message)}}
async function storiesOnline(){const epoch=O.epoch,data=await remote('GET',`/v1/stories?radius_km=${state.radiusKm}`);if(epoch!==O.epoch)return;O.stories=data.stories||[];state.stories=O.stories.filter(s=>s.user_id===O.me.user_id).map(s=>({...s.payload,id:s.id,time:Date.parse(s.created_at)}));if(tab==='near'&&!document.querySelector('.overlay'))renderNearby100();}
function storyItemsOnline(user){return O.stories.filter(s=>s.user_id===user).map(s=>({...s.payload,id:s.id,time:Date.parse(s.created_at)}))}
storyStrip=function(){let own=activeStories();let list=people.filter(p=>O.near.has(p.id)&&!state.blocked.includes(p.id)&&storyItemsOnline(p.user_id).length);return `<div class="stories"><button class="story" onclick="${own.length?'ownStory(0)':'addStory()'}"><div class="ring ${own.length?'':'blank'} ${own.length&&own.every(s=>state.storySeen['own-'+s.id])?'seen96':''}"><img src="${esc(state.photo||'p0.svg')}" alt="La tua storia"></div>${own.length?'':'<span class="plusbadge">+</span>'}<span>La tua storia</span></button>${own.length?`<button class="story" onclick="addStory()"><div class="storyadd">${icon('plus')}</div>Aggiungi</button>`:''}${list.map(p=>`<button class="story" onclick="story(${p.id})"><div class="ring ${storyItemsOnline(p.user_id).every(s=>state.storySeen['demo-'+p.id+'-'+s.id])?'seen96':''}"><img src="${esc(p.photo||'p0.svg')}" alt=""></div>${esc(p.name)}</button>`).join('')}</div>`};
story=function(id){const items=storyItemsOnline(people[id]?.user_id);if(!items.length)return toast('Nessuna storia attiva');let page=document.querySelector('.profilepage:not(.ownpreview9)');storyOrigin96=page?{id,fromChat:profileContext96?.fromChat||false,scroll:page.scrollTop}:null;O.pageChat=null;viewStory({own:false,id,index:0,items})};
publish=async function(){const text=document.querySelector('#storytext').value.trim();if(!text&&!storyDraft.image)return toast('Aggiungi una foto o una frase');const b=document.querySelector('.overlay .primary');if(b)b.disabled=true;try{await remote('POST','/v1/stories',{text,image:storyDraft.image,color:storyDraft.color});await storiesOnline();closeOverlay();show('near');ownStory(activeStories().length-1);toast('Storia pubblicata')}catch(e){toast(e.message);if(b)b.disabled=false}};
deleteStory=async function(id){try{await remote('DELETE','/v1/stories/'+id);await storiesOnline();closeOverlay();show('near');toast('Storia eliminata')}catch(e){toast(e.message)}};
reactStory=async function(id,reaction){const item=storySession?.items[storySession.index];if(!item)return;try{await sendContentOnline(id,{type:'storyReply',reaction,story_id:item.id});toast('Reazione inviata')}catch(e){toast(e.message)}};
sendStoryReply=async function(id){const input=document.querySelector('#storyreplytext'),text=input?.value.trim(),item=storySession?.items[storySession.index];if(!text||!item)return;try{await sendContentOnline(id,{type:'storyReply',text,story_id:item.id});input.value='';document.querySelector('.storyreplyform')?.remove();toast('Risposta inviata')}catch(e){toast(e.message)}};
const voiceRenderOriginalOnline=renderMe;renderMe=function(){voiceRenderOriginalOnline();polishOnline()};
extra101=function(){return false};setDemoPlan101=function(){toast('Gli acquisti non sono ancora attivi.')};demoActivity102=function(){};
const planOriginalOnline=planPage101;planPage101=function(){O.pageChat=null;planOriginalOnline();polishOnline()};
async function albumsOnline(){const epoch=O.epoch,revision=O.albumRevision,data=await remote('GET','/v1/me/albums');if(epoch!==O.epoch||revision!==O.albumRevision)return;const before=JSON.stringify(state.albums);state.albums=(data.albums||[]).map(a=>({...a,id:a.id,slot101:1}));if(before!==JSON.stringify(state.albums)){renderStateOnline();if(document.querySelector('.albumspage98'))managerOriginalOnline()}}
const managerOriginalOnline=albumManager9;albumManager9=async function(){O.pageChat=null;try{await albumsOnline();managerOriginalOnline()}catch(e){toast(e.message)}finally{O.albumRevision++}};
const editAlbumOriginalOnline=editAlbum9;editAlbum9=function(id){editAlbumOriginalOnline(id);if(albumDraft9&&!id)albumDraft9.id=crypto.randomUUID()};
saveAlbum9=async function(){captureAlbum9();if(!albumDraft9.name.trim()||!albumDraft9.photos.length)return toast('Aggiungi un nome e almeno una foto');if(O.albumSaving)return;O.albumSaving=true;O.albumRevision++;const draft={...albumDraft9};const buttons=[...document.querySelectorAll('.albumedit98 button')];buttons.forEach(b=>b.disabled=true);try{const saved=await remote('PUT','/v1/me/albums/'+draft.id,{name:draft.name.trim(),photos:draft.photos});state.albums=[...state.albums.filter(a=>a.id!==draft.id),{...draft,...saved,slot101:1}];albumDraft9=null;renderStateOnline();managerOriginalOnline();toast('Album salvato')}catch(e){toast('Salvataggio non riuscito: '+e.message)}finally{O.albumRevision++;O.albumSaving=false;buttons.forEach(b=>b.disabled=false)}};

confirmAlbumDelete9=function(id){overlay(`<h1>Eliminare l’album?</h1><p>Le copie già condivise rimangono nelle chat.</p><button class="primary wide" onclick="deleteAlbumOnline('${id}')">Elimina album</button>`)};
async function deleteAlbumOnline(id){O.albumRevision++;try{await remote('DELETE','/v1/me/albums/'+id);state.albums=state.albums.filter(a=>a.id!==id);renderStateOnline();managerOriginalOnline()}catch(e){toast(e.message)}finally{O.albumRevision++}}
const shareOriginalOnline=chooseAlbum9;chooseAlbum9=async function(id){O.pageChat=null;try{await albumsOnline();shareOriginalOnline(id)}catch(e){toast(e.message)}};
sendAlbum9=async function(id,albumId,temporary){try{await sendContentOnline(id,{type:'album',album_id:albumId,temporary});await chat(id)}catch(e){toast(e.message)}};
async function syncChatsOnline(){const epoch=O.epoch,data=await remote('GET','/v1/chats');if(epoch!==O.epoch)return;let changed=JSON.stringify(O.chats)!==JSON.stringify(data.chats);O.chats=data.chats||[];for(const row of O.chats){const id=person(row);state.chatActivity[id]=Date.parse(row.created_at);if(!state.messages[id]?.length||state.messages[id].every(m=>m.preview))state.messages[id]=[{type:'text',text:row.last_message,time:Date.parse(row.created_at),preview:true}]}
if(changed&&tab==='chat'&&!document.querySelector('.overlay')){const open=[...document.querySelectorAll('.swiperow95.open')].map(e=>e.dataset.chatId);renderChats();for(const el of document.querySelectorAll('.swiperow95'))if(open.includes(el.dataset.chatId))el.classList.add('open');polishOnline()}}
chats6=function(){return O.chats.map(c=>people[O.ids.get(c.user_id)]).filter(p=>p&&!state.blocked.includes(p.id))};

function renderCurrentMessagesOnline(id){const body=document.querySelector('.chatbody');if(!body||O.pageChat!==id)return;body.innerHTML=(state.messages[id]||[]).map((m,i)=>`<div class="bubble ${m.outgoing103?'':'incomingOnline'}" data-message-index97="${i}">${messageHTML(m,id,i)}<div class="smallnote" style="text-align:right">${new Date(m.time).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}${m.outgoing103?' · Inviato':''}</div></div>`).join('');body.scrollTop=body.scrollHeight}
const previewOriginalOnline=chatPreview97;chatPreview97=function(id){const row=O.chats.find(c=>c.user_id===people[id]?.user_id);return row?.last_message||previewOriginalOnline(id)};
const chatListOriginalOnline=chatList;chatList=function(ps){const wrapper=document.createElement('div');wrapper.innerHTML=chatListOriginalOnline(ps);for(const row of wrapper.querySelectorAll('.swiperow95')){const id=Number(row.dataset.chatId),convo=O.chats.find(c=>c.user_id===people[id]?.user_id),count=convo?.unread_count||0;if(count){const badge=document.createElement('b');badge.className='chatunreadOnline';badge.textContent=count>99?'99+':String(count);row.querySelector('.chatrow5').append(badge)}}return wrapper.innerHTML};

const chatOriginalOnline=chat;chat=async function(id,draft){if(!people[id]||state.blocked.includes(id))return;O.pageChat=id;chatOriginalOnline(id,draft);try{await syncChatsOnline();await messagesOnline(id,true)}catch(e){toast(e.message)}};
async function messagesOnline(id,initial=false){const convo=O.chats.find(c=>c.user_id===people[id].user_id);if(!convo)return;if(O.pageChat!==id)return;const epoch=O.epoch,previous=state.messages[id]||[],after=initial?0:Math.max(0,...previous.map(m=>m.server_id||0));const data=await remote('GET',`/v1/chats/${convo.id}/messages?after=${after}&limit=200`);if(epoch!==O.epoch||O.pageChat!==id)return;let map=new Map((initial?[]:previous).filter(m=>m.server_id).map(m=>[m.server_id,m]));for(const row of data.messages||[])map.set(row.id,{...row.payload,server_id:row.id,server_sender:row.sender,time:Date.parse(row.created_at),outgoing103:row.sender===O.me.user_id,direction:row.sender===O.me.user_id?'outgoing':'incoming'});state.messages[id]=[...map.values()].sort((a,b)=>a.server_id-b.server_id);if(!document.hidden&&window.prismForeground!==false&&O.pageChat===id){await remote('POST','/v1/chats/'+convo.id+'/read',{through:Math.max(0,...state.messages[id].map(m=>m.server_id||0))});if(O.notifications){const removed=O.notifications.items.filter(n=>n.conversation_id===convo.id).length;O.notifications.items=O.notifications.items.filter(n=>n.conversation_id!==convo.id);O.notifications.counts.message=Math.max(0,O.notifications.counts.message-removed);const item=O.chats.find(c=>c.id===convo.id);if(item)item.unread_count=0;drawNoticesOnline()}}if(document.querySelector('.chatpage')&&O.pageChat===id){const input=document.querySelector('#message'),value=input?.value||'',focused=document.activeElement===input;const start=input?.selectionStart,end=input?.selectionEnd;const box=document.querySelector('.chatbody'),scroll=box?.scrollTop||0,bottom=box&&box.scrollHeight-box.scrollTop-box.clientHeight<100;if(initial){chatOriginalOnline(id,value)}else if(data.messages?.length){box.innerHTML=state.messages[id].map((m,i)=>`<div class="bubble ${m.outgoing103?'':'incomingOnline'}" data-message-index97="${i}">${messageHTML(m,id,i)}<div class="smallnote" style="text-align:right">${new Date(m.time).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}${m.outgoing103?' · Inviato':''}</div></div>`).join('');box.scrollTop=bottom?box.scrollHeight:scroll}if(focused&&initial){const current=document.querySelector('#message');current.focus();current.setSelectionRange(start,end)}}}
async function sendContentOnline(id,payload){let task=O.sendTasks.get(id);const key=JSON.stringify(payload);if(!task||task.key!==key){task={key,client_id:crypto.randomUUID()};O.sendTasks.set(id,task)}const row=await remote('POST','/v1/chats/'+people[id].user_id+'/content',{client_id:task.client_id,payload});O.sendTasks.delete(id);const list=(state.messages[id]||[]).filter(m=>m.server_id);if(!list.some(m=>m.server_id===row.id))list.push({...row.payload,server_id:row.id,time:Date.parse(row.created_at),outgoing103:true});state.messages[id]=list;state.chatActivity[id]=Date.parse(row.created_at);await syncChatsOnline();return row}
appendMessage=function(){toast('Invio in corso: usa il pulsante di conferma.');return false};
send=async function(e,id){e.preventDefault();let input=document.querySelector('#message'),text=input.value.trim(),button=e.target.querySelector('.send');if(!text||button?.disabled)return;if(button)button.disabled=true;try{await sendContentOnline(id,{type:'text',text,...(replySelection97?.id===id?{quote:replySelection97.quote}:{})});state.chatDrafts[id]='';replySelection97=null;if(O.pageChat===id){if(input.value.trim()===text)input.value='';renderCurrentMessagesOnline(id);await notificationsOnline()}}catch(error){toast(error.message)}finally{if(button)button.disabled=false}};
sendChatPhoto=async function(){if(!pendingPhoto)return;const p=pendingPhoto;try{await sendContentOnline(p.id,{type:p.temporary?'temporary':'photo',data:p.image});pendingPhoto=null;await chat(p.id)}catch(e){toast(e.message)}};
sendVoice8=async function(){if(!voiceDraft8)return;const draft=voiceDraft8;try{await sendContentOnline(draft.id,{type:'voice',data:draft.data,duration:draft.duration});voiceDraft8=null;await chat(draft.id)}catch(e){toast(e.message)}};
deleteChat95=async function(id){const conv=O.chats.find(c=>c.user_id===people[id].user_id);if(!conv)return;try{await remote('DELETE','/v1/chats/'+conv.id);O.chats=O.chats.filter(c=>c.id!==conv.id);delete state.messages[id];delete state.chatActivity[id];delete state.chatDrafts[id];closeOverlay();show('chat');toast('Chat eliminata')}catch(e){toast(e.message)}};
outgoing103=function(m){return m?.outgoing103===true||m?.direction==='outgoing'};
const temporaryOriginalOnline=openTemporary;openTemporary=async function(id,index){let m=state.messages[id]?.[index];if(!m)return;if(m.outgoing103)return temporaryOriginalOnline(id,index);try{let row=await remote('POST','/v1/messages/'+m.server_id+'/open');const data=row.payload.data;state.messages[id][index]={...m,viewed:true};overlay(`<div class="timerlabel">Foto visualizzabile una volta · 10 secondi</div><img src="${esc(data)}" alt="Foto temporanea"><button class="pill" onclick="chat(${id})">Torna alla chat</button>`,'mediafull');tempTimer=setTimeout(()=>{if(document.querySelector('.mediafull'))chat(id)},10000)}catch(e){toast(e.message)}};
const openAlbumOriginalOnline=openAlbum9;openAlbum9=async function(id,index){let m=state.messages[id]?.[index];if(!m)return;if(m.outgoing103||!m.temporary)return openAlbumOriginalOnline(id,index);try{let row=await remote('POST','/v1/messages/'+m.server_id+'/open');state.messages[id][index]={...m,viewed:true};albumSession9={id,index,name:m.name,photos:row.payload.photos,position:0,deadline:Date.now()+60000};renderAlbumViewer9()}catch(e){toast(e.message)}};
const messageOriginalOnline=messageHTML;messageHTML=function(m,id,index){if(m.type==='album'&&!m.outgoing103&&m.temporary&&!m.viewed)return `<button class="albumbubble9" onclick="openAlbum9(${id},${index})">${icon('clock')}<span><b>${esc(m.name)}</b><small>Apri una volta · 60 secondi</small></span></button>`;const html=messageOriginalOnline(m,id,index);return m.outgoing103===false&&m.type==='storyReply'?html.replace('LA TUA REAZIONE','REAZIONE RICEVUTA').replace('LA TUA RISPOSTA','RISPOSTA RICEVUTA'):html};
logout=async function(){try{await remote('POST','/v1/auth/logout');resetOnline();auth('login')}catch(e){toast(e.message)}};
deleteAccountPage=function(){overlay(`<h1>Eliminare il tuo account?</h1><p>Questa operazione elimina l’account e i tuoi dati dal servizio.</p><form onsubmit="deleteOnline(event)"><label>Email<input id="delete_email" type="email" required></label><label>Password<input id="delete_password" type="password" minlength="12" required></label><button class="primary wide">Elimina definitivamente</button></form>`)};
async function deleteOnline(e){e.preventDefault();try{await remote('DELETE','/v1/me',{email:document.querySelector('#delete_email').value,password:document.querySelector('#delete_password').value});resetOnline();auth('register');toast('Account eliminato')}catch(error){toast(error.message)}}
async function syncOnline(){await remote('POST','/v1/me/heartbeat');await Promise.all([activityOnline(),syncChatsOnline(),storiesOnline(),albumsOnline(),blockedOnline(),favoritesOnline(),notificationsOnline()])}
window.prismResume=async function(){if(!O.me||document.hidden||window.prismForeground===false||O.polling)return;O.polling=true;try{const chatId=O.pageChat;await Promise.all([syncChatsOnline(),activityOnline(),favoritesOnline(),albumsOnline(),blockedOnline()]);if(chatId!==null&&document.querySelector('.chatpage'))await messagesOnline(chatId);await notificationsOnline();if(++O.pollRound%5===0){await remote('POST','/v1/me/heartbeat');if(O.me.latitude!=null){await nearbyOnline();await storiesOnline()}}}catch(e){O.syncError=e.message}finally{O.polling=false}};O.pollRound=0;
window.prismBack=()=>{if(document.querySelector('.overlay')){O.pageChat=null;closeOverlay()}else if(window.signedIn)show('near');else auth('login')};setInterval(()=>window.prismResume(),2000);
let soundContextOnline=null,soundMutedOnline=localStorage.getItem('prism-sound-muted')==='true';
document.addEventListener('pointerdown',()=>{try{soundContextOnline||=new (window.AudioContext||window.webkitAudioContext)();soundContextOnline.resume()}catch{}},{passive:true});
function noticeSoundOnline(){if(soundMutedOnline||!soundContextOnline||soundContextOnline.state!=='running')return;const oscillator=soundContextOnline.createOscillator(),gain=soundContextOnline.createGain(),now=soundContextOnline.currentTime;oscillator.type='sine';oscillator.frequency.setValueAtTime(880,now);oscillator.frequency.setValueAtTime(1174,now+.09);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.12,now+.02);gain.gain.exponentialRampToValueAtTime(.0001,now+.23);oscillator.connect(gain);gain.connect(soundContextOnline.destination);oscillator.start(now);oscillator.stop(now+.25)}
function noticeLabelOnline(n){return n.kind==='message'?`${n.name||'Qualcuno'} ti ha inviato un messaggio`:n.kind==='tap'?`${n.name||'Qualcuno'} ti ha inviato un Tap`:'Qualcuno ha visitato il tuo profilo'}
async function notificationsOnline(){const epoch=O.epoch,data=await remote('GET','/v1/notifications');if(epoch!==O.epoch)return;const initialized=O.notifications!==null;const fresh=(data.items||[]).filter(n=>!O.seenNotices.has(n.key));O.notifications=data;for(const n of data.items||[])O.seenNotices.add(n.key);if(initialized&&fresh.length){const visible=fresh.filter(n=>!(n.kind==='message'&&O.chats.find(c=>c.id===n.conversation_id)?.user_id===people[O.pageChat]?.user_id));if(visible.length){noticeSoundOnline();document.querySelector('.noticebannerOnline')?.remove();const banner=document.createElement('button');banner.className='noticebannerOnline';banner.setAttribute('role','status');banner.textContent=visible.length===1?noticeLabelOnline(visible[0]):`${visible.length} nuove attività su PRISM`;banner.onclick=()=>openNotificationsOnline();document.body.append(banner);setTimeout(()=>banner.remove(),5000)}}drawNoticesOnline();ackActivityOnline();if(document.querySelector('.notificationcenterOnline'))renderNotificationsOnline()}
function drawNoticesOnline(){const counts=O.notifications?.counts||{};for(const [label,total] of [['Tap',(counts.tap||0)+(counts.visit||0)],['Chat',counts.message||0]]){const button=document.querySelector(`#nav button[aria-label="${label}"]`);if(!button)continue;const existing=button.querySelector('.navbadgeOnline');if(total){if(!existing){const badge=document.createElement('b');badge.className='navbadgeOnline';button.append(badge)}const badge=button.querySelector('.navbadgeOnline'),value=total>99?'99+':String(total);if(badge.textContent!==value)badge.textContent=value;button.setAttribute('aria-description',`${total} non letti`)}else{existing?.remove();button.removeAttribute('aria-description')}}const heading=document.querySelector('.nearheading100,.pageheading98,.wrap:has(.chatlisttitle)');if(heading&&!heading.querySelector('.notificationbellOnline')){const button=document.createElement('button');button.className='notificationbellOnline';button.setAttribute('aria-label','Notifiche');button.innerHTML='<svg class="icon" viewBox="0 0 24 24"><path d="M18 8a6 6 0 0 0-12 0v5l-2 4h16l-2-4z M9 21h6"/></svg>';button.onclick=openNotificationsOnline;heading.append(button)}}
async function ackActivityOnline(){if(tab!=='taps'||document.querySelector('.overlay')||!O.notifications)return;const kind=tapTab==='views'?'visit':tapTab==='received'?'tap':null;if(!kind||!O.notifications.counts[kind])return;const through=O.notifications.as_of,key=kind+through;if(O.readTasks.has(key))return;O.readTasks.add(key);try{await remote('POST','/v1/notifications/read-activity',{kind,through});if(O.notifications.as_of===through){O.notifications.counts[kind]=0;O.notifications.items=O.notifications.items.filter(n=>n.kind!==kind);drawNoticesOnline()}}catch{}finally{O.readTasks.delete(key)}}
function openNotificationsOnline(){O.pageChat=null;overlay('','notificationcenterOnline');renderNotificationsOnline()}
function renderNotificationsOnline(){const page=document.querySelector('.notificationcenterOnline');if(!page)return;const items=O.notifications?.items||[];page.innerHTML=toolbar98('Notifiche','Tap, visite e messaggi','closeOverlay()')+`<div class="pagebody98"><button class="notificationsoundOnline" onclick="toggleNoticeSoundOnline()">${icon('mic')} Suoni ${soundMutedOnline?'disattivati':'attivi'}</button>${items.map((n,i)=>`<button class="notificationrowOnline" onclick="openNoticeOnline(${i})"><span>${icon(n.kind==='message'?'chat':n.kind==='tap'?'bolt':'eye')}</span><div><b>${esc(noticeLabelOnline(n))}</b><small>${new Date(n.created_at).toLocaleString('it-IT',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</small></div>${icon('chevron')}</button>`).join('')||'<div class="empty"><h2>Sei al passo.</h2><p>Nessuna attività non letta.</p></div>'}</div>`}
function toggleNoticeSoundOnline(){soundMutedOnline=!soundMutedOnline;localStorage.setItem('prism-sound-muted',String(soundMutedOnline));renderNotificationsOnline();if(!soundMutedOnline)noticeSoundOnline()}
async function openNoticeOnline(index){const notice=O.notifications?.items[index];if(!notice)return;if(notice.kind==='message'){await syncChatsOnline();const id=O.ids.get(notice.user_id);if(id!==undefined)chat(id)}else{tapTab=notice.kind==='tap'?'received':'views';closeOverlay();show('taps')}}
function fitChatViewportOnline(){const page=document.querySelector('.chatpage');if(!page)return;const viewport=window.visualViewport;page.style.top=(viewport?.offsetTop||0)+'px';page.style.height=(viewport?.height||innerHeight)+'px';page.style.bottom='auto';page.style.width='100%';page.style.maxWidth='650px'}
window.visualViewport?.addEventListener('resize',fitChatViewportOnline);window.visualViewport?.addEventListener('scroll',fitChatViewportOnline);window.addEventListener('resize',fitChatViewportOnline);document.addEventListener('focusin',e=>{if(e.target.id==='message'){fitChatViewportOnline();setTimeout(fitChatViewportOnline,300)}});

const readPhotoOriginalOnline=readPhoto;readPhoto=function(input,done){readPhotoOriginalOnline(input,data=>{const image=new Image();image.onload=()=>{const scale=Math.min(1,800/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);let value=canvas.toDataURL('image/jpeg',.7);if(value.length>220000)value=canvas.toDataURL('image/jpeg',.45);if(value.length>220000)return toast('Questa foto è troppo grande. Scegli un’altra immagine.');done(value)};image.src=data})};
function fixImagesOnline(root=document){for(const img of root.querySelectorAll('img')){const match=(img.getAttribute('src')||'').match(/^p(\d+)\.svg$/);if(match){let p=people[Number(match[1])];const own=img.closest('.my98,.auth95,.editor98')||img.classList.contains('navavatar9')||img.alt==='La tua storia';const photo=own?state.photos?.[0]:p?.photo;if(photo)img.src=photo;else img.setAttribute('src','placeholder.svg')}}}
new MutationObserver(()=>{fixImagesOnline();polishOnline();drawNoticesOnline();fitChatViewportOnline()}).observe(document.body,{childList:true,subtree:true});
(async()=>{try{await enterOnline()}catch(e){auth('login');if(e.status!==401)toast(e.message)}finally{setTimeout(finishBoot94,500)}})();
